### ISSUE TITLE
a .block property of CCNode causes a retain cycle

### ISSUE THREAD

**Issue by YvesLeBorg** [cocos2d/cocos2d-objc#1000]
Trying to figure out why one of my classes was not deallocating, i found i had to nil out one of it's childrens' block 

```
- (void)onExit {
    [super onExit];
    [self stopAllActions];
    if (_isSettingsDirty) [[BattlesStatus sharedBattlesStatus] doSave];
    self.menuTag             = nil;
    self.consumer            = nil;
    self->_creditsMenu.block = nil; // should not have to do this, CCNode should release the block onExit

    ...

}
```

I think CCNode should do that in its own onExit implementation.

**Comment by iMobCoding** [comment]
You should show a code where you defined that block. I am sure you made the retained cycle by not using weak instances inside...

**Comment by YvesLeBorg** [comment]
here is where block is set (is is self that was not deallocating). 

```
__block  CCNode *selfie = self;
 _creditsMenu.block = ^(id sender) {
        MPQuickCredits *quickCredits = [MPQuickCredits quickCredits];
        [selfie addChild:quickCredits];
    };
```

and here is CCNode's property for block (in CCControl.h)  (i messed up the title, is CCControl)

```
@property (nonatomic,copy) void(^block)(id sender);
```

I am currently upgrading my game (and self) to cocos2d 3.2.1 and ARC ... so please tell me how i should have setup this correctly. Also, is not the copy property modifier creating a retain cycle on the copy ?

**Comment by ghost** [comment]
Change:

 __block  CCNode *selfie = self;

to 

__weak  CCNode *selfie = self;

**Comment by YvesLeBorg** [comment]
yep ... although it would not be a bad idea to nil out block on exit. It is CCControl's own copy, it is exiting, has no further use for it. .02

**Comment by ghost** [comment]
I'm not sure if this changed in V3 because I hardly ever do this, but if you 'push' a scene onto the stack instead of replacing I'm pretty sure onExit gets called? If you pop it off and go back, your block can be nil when you're really not done with it (unless CCControl sets its block in onEnter). I'm not looking at the source right now...but doesn't onExit get called when you do that? In that case, you wouldn't want to nil the block out in onExit. Unless it's your class for your project and you know you'll never push a scene on it.

Can nil it out in dealloc, but that wouldn't break a retain cycle if you didn't use a weak reference to self, because the block will keep the self alive so dealloc won't be called on self and the block won't get set to nil. It does feel kind of obnoxious to have to write out _
_weak when using blocks a lot, but I've trained myself to almost always use weak references within blocks when referring to self or any ivars or properties. It doesn't bother me as much anymore.

**Comment by YvesLeBorg** [comment]
onExit gets called when a node is removed from its parent, this is why i was saying that it is a good place to nil out block ... but !!!  some people could remove a node from one parent with the intent of later adding the node to another parent (that is the purpose of the 'cleanup' parameter on any removeChild or removeFromParent methods). WIth that said, i withdraw my .02 ... nilling on exit would break that somewhat contorted but valid use case. I closed the bug ... i'll clean my mess __weakly;

Regarding scenes, you should also consider that some people (like me) only ever use one scene, the start scene, although my games are full of cut-scenes etc ... my code looks like: 

[battleSequencer cleanForNextScene];
[gameSequencer loadChapter:currentChapter+1];
[battleSequencer sequenceNewChapter];

and make certain that everything gets properly dealloc'ed (this is how i became aware of the retain cycle in the first place, was not getting log telling me that the object had dealloc'ed) My game designer has some pretty set ideas about transitions, and i cant really use the ones you provide in cocos2d. In the example above, the battleSequencer object knows how to transition between chapters.
