### ISSUE TITLE
There is a limit to how big a batch can get.

### ISSUE THREAD

**Issue by killerham** [cocos2d/cocos2d-objc#1002]
Forum reference: http://forum.cocos2d-swift.org/t/maximum-number-of-verticies-v3-2/15117/4

The renderer uses indexed rendering, and as this uses a GL_UNSIGNED_SHORT as index, it means that there is a limit to how big a batch can get.

The GL ES 2 spec only supports up to 16 bit vertex index types, which is why it caps out at 64k vertexes. Currently it doesn't even fail gracefully which is the bigger problem.

slembcke suggested to just break them into "pages" of 64k vertexes within the same large buffer. Tracking that is a lot simpler, and changing the offset within a single large buffer is simpler than moving/mapping multiple buffers.

**Comment by slembcke** [comment]
I've started working on this last week before getting sick. Should be my next priority to fix.

**Comment by killerham** [comment]
Okay sounds good!

**Comment by slembcke** [comment]
Vertex pages have been implemented in the develop (3.3 beta) branch. Backporting the changes to v3.2 is going to require a separate implementation since there were a lot of GL updrades in 3.3 (in addition to the Metal ones).

Since this issue has only come up a few times, how many people really need this implemented in 3.2?

**Comment by killerham** [comment]
That great!

It depends on when 3.3 will become a stable branch.
