### ISSUE TITLE
CCEffect Issue Sprite Sheet

### ISSUE THREAD

**Issue by cocojoe** [cocos2d/cocos2d-objc#1024]
Have filed this one under SpriteBuilder however the underlying issue must be in Cocos2D.

Spritebuilder/Spritebuilder#969

**Comment by slembcke** [comment]
Should be fixed in https://github.com/cocos2d/cocos2d-swift/pull/1027

**Comment by iMobCoding** [comment]
There is still a bug with CCEffect and sprite sheet when sprites are trimmed. At least I tried with Bloom effect and latest commit of v1.4 branch

**Comment by thayerandrews** [comment]
Have you tried adjusting the padding value of the bloom effect?  The
padding subtest in CCEffectsTest demonstrates how to use padding to avoid
clipping of sprites with effects that expand the visual size of the
affected sprite (bloom, blur, color channel offset).

If you're still seeing problems after adjusting the padding, please let me
know.

**Comment by iMobCoding** [comment]
Hi

Tried with padding, but same wrong results. Attached how wrong gloom looks like (like it's horiz scaled because of wrong frame size) and how correct one looks...
![wrong](https://cloud.githubusercontent.com/assets/1320690/6272879/5d51e6ec-b86b-11e4-836e-6162709d8b53.jpg)
![correct](https://cloud.githubusercontent.com/assets/1320690/6272882/602c6522-b86b-11e4-8b31-5245de1a6e41.jpg)

**Comment by thayerandrews** [comment]
Got it. Thanks for demonstrating the problem.
