### ISSUE TITLE
Critical issue with shaders. 

### ISSUE THREAD

**Issue by s1ddok** [cocos2d/cocos2d-objc#1281]
I've been developing a game with cocos2d v3.4 and Swift 1.2 beta via XCode 6.3 beta 2.

The development stage got me to start creating shaders for my game, they are essential.
I was developing using simulator and everything worked (and still working actually) just fine. Perfect and smooth with no problems, but as I compiled my prototype for a mobile device I met an awful problem which harassing me a lot.

The problem is that all of the shaders gets ugly with time. They keep getting pixelated as the time goes and the more complex the shader the faster it gets pixelated. My first thought was that it is becuase of Swift 1.2 beta, but I still opened a topic on stackoverflow (http://stackoverflow.com/questions/29320983/ios-opengl-shaders-get-ugly-and-freezy-with-time) and cocos2d-forum (http://stackoverflow.com/questions/29320983/ios-opengl-shaders-get-ugly-and-freezy-with-time). There are some versions on what's going on. But then I decided to check if it is a Swift 1.2 problem or a general issue and just compiled a cocos2d shader cookbook for my device and faced the same exact problem.

Here is the video of how it looks:
http://www.youtube.com/watch?v=Cch_KvnaIP0
I recorded it from my iPhone 6 Plus but the problem also appears on iPad Air. I haven't tested that on my other devices yet. Both iPhone and iPad running iOS8. I didnt speed up the video so you should skip it and see the effect.

I'm sorry for my english but I found this problem very critical and want it to be fixed as soon as possible.

Then again: everything works just GREAT on the simulator. The problem appears on devices only.

**Comment by slembcke** [comment]
This isn't a bug, and it cannot be fixed in Cocos2D or OpenGL. It's a precision problem that you will have to deal with in your code.

The simulator uses 32 bit floating point math in it's GLSL implementation. Real hardware isn't required to do this, and it rarely does unless your are using a desktop GPU. Fragment shaders in particular can run into problems since they are only required to implement 16 bit floating point math, which isn't very accurate. cc_Time in particular has problems in a fragment shader since the value will keep getting bigger and bigger. Move your calculations into the vertex shader, or into Obj-C code if you can. You are guaranteed 32 bit precision there.

More info here: http://forum.cocos2d-spritebuilder.org/t/shader-uniform-vs-precision/15032
