### ISSUE TITLE
website's forum doesn't work

### ISSUE THREAD

**Issue by gerchicov-bp** [cocos2d/cocos2d-objc#1385]
I don't know where to post this bug.
Both forum registration and password restoring don't work:
http://forum.cocos2d-objc.org/

And additionally I want to ask about PureSwift - does it mean you won't develop obj-c version and it is strongly recommended to use swift?

**Comment by s1ddok** [comment]
Don't worry. PureSwift as it was intendet will not appear for now, since kickstarter campaign failed, so -objc will be supported.

As for registration I dont have access to hosting and even If I had I still dont think I can do anything about it since I'm not a web developer. I will forward this issue to @Birkemose.

**Comment by Birkemose** [comment]
Ugh ...  
Seems that MailChimp recently stopped their free service, meaning we have to switch to ex. MailGun.
I will see if I can get it fixed tomorrow.
