### ISSUE TITLE
Could you please upgrade the cocos2d-objc version on cocoapod?

### ISSUE THREAD

**Issue by flyingdog1** [cocos2d/cocos2d-objc#1387]
My project needs to use cocos2d-objc on the platform of cocoapod. But the problem is that the highest version published on cocoapod is "cocos2d-3.1.0-alpha", which can not match my spritebuilder version.  My spritebuilder version is 1.5.0, I desperately want a version named "cocos2d-3.5.0" on cocoapod. Could you please upgrade the cocos2d-objc version on cocoapod? thanks a lot!

**Comment by s1ddok** [comment]
Ugh, the problem is cocoapods was never supported officially. They always were fan-made. This happens because cocos2d can't really be installed as a cocoapod, as it needs some templating in the project structure (for example `CCAppDelegate`, which I personally hate). I do not think cocoapods will appear for v3.5.

**Comment by flyingdog1** [comment]
I wonder if there is a SDK for users, because I don't want to create a new project. I need to add the cocos2d environment to my iphone application project.

**Comment by s1ddok** [comment]
You can do it manually. Tests application can you give you an idea how to do that

**Comment by flyingdog1** [comment]
Ok, Thank you for answering.
