### ISSUE TITLE
Cocos2d tests

### ISSUE THREAD

**Issue by vlidholt** [cocos2d/cocos2d-objc#349]
Relevant old tests needs to be converted to new test format.

Some thoughts on new tests:

The old tests uses lots of animations and are fun to watch, but that makes them hard to automate. An idea is to make as many of the tests as possible static and without user interaction. It may be boring to watch, but we could use screen shots to verify that they are working. Naturally, many test are not possible to do in a static way.

New tests should work on both iPhone and iPad.

If possible, someone watching the test should be able to tell if a test is working or failing. A descriptive sub-title of what is supposed to happen is a good practice.

**Comment by slembcke** [comment]
A lot of the tests should be moved to automated unit tests as well. Running more that one test by hand quickly turns into an error prone waste of time. It's not always clear what all of the tests are supposed to do either (even given a description) so it's difficult to know if they are working correctly or not.

**Comment by vlidholt** [comment]
Do you have any experience with automated tests and suggestions for how to best do this? I guess for Cocos2d often the output of the tests are very visual, so I am thinking of writing a program that outputs screen shots that can be compared with stored 'correct' screens shots.

**Comment by slembcke** [comment]
Yes. There are a small smattering of them for Chipmunk, and like... one so far for CCPhysics. For instance:
https://github.com/slembcke/Chipmunk2D/blob/master/xcode/ObjectiveChipmunkTests/SpaceTest.m

XCode's 4.x's unit testing system is ok, though there are quite a few UI bugs. Unit testing visual stuff is usually not very productive. Comparing screenshots often doesn't work since OpenGL allows for invariance (i.e. it doesn't enforce that renderers should match pixel for pixel). There are plenty of things that can be effectively unit tested though. Run the scheduler in a for loop and check that it calls the correct callbacks, check that actions have approximately the desired effect over time. Check that setting or changing nodes has the desired effect by checking their transform matrices. Does cached textures get freed when changing scenes and purging the cache?

I usually find that when you go looking for bugs, you'll always find them. ;) Having a nice set of unit tests helps ensure that you can fix those bugs without causing new ones. The bigger a project gets the more likely that is to start happening.

**Comment by vlidholt** [comment]
My idea for comparing screenshots is to use a program that does fuzzy comparisons. Say it's a 95% match and it passes.

I'll be reading up on the Xcode unit tests! Maybe there should be a combination of unit tests, comparison of screenshots and for some cases manual testing? I think it may be hard to avoid manual testing all together for things such as touch handling, visually confirming animations etc.

**Comment by ghost** [comment]
@vlidholt I use imagemagick for fuzzy image comparison, here is the command:

`/opt/local/bin/compare -metric AE -fuzz 10% ${IMAGE_ONE} ${IMAGE_TWO} diff.png 2>&1`

**Comment by slembcke** [comment]
Well, I like I said, it's definitely possible to do image based testing, but it has perhaps the lowest effort to utility ratio of anything you could do. Ideally you want simple tests and check simple conditions so that it's clear what the test actually does and which parts it's testing.

Fuzzy image comparisons are generally very poorly defined what they actually do, and they are unlikely to catch a lot of obvious pixel level artifacts. It's also sort of a chicken and egg problem. If you are testing the output of a program against it's own output (which may be wrong to begin with) instead of constructing the expected output, you are unlikely to find any real bugs.

Unit tests + a handful of visual demos has worked ok for Chipmunk. I've never attempted to automate checking renderer output and I've heard a lot of bad experiences from people that have tried due to the above problems.
