### ISSUE TITLE
Templates not working

### ISSUE THREAD

**Issue by vlidholt** [cocos2d/cocos2d-objc#350]
Templates in V3 are currently not working correctly. What needs to be done to fix them?

**Comment by slembcke** [comment]
A note to whoever does end up fixing them, Cocos2D should be moved to a static library target so it doesn't need to share the same build settings as the rest of a user's project.

Has anybody ever worked with Xcode templates before?

**Comment by Panajev** [comment]
I agree, Cocos2D should move to a static library project and should also need to test for many more warnings and treat them as errors. I made a pull request result of a fair bit of work, but received no comment so far.

I modified the Cocos2D templates a bit before to support a static library version of Cocos2D (CocosLib on GitHub and related template projects), but it was a tad more limited effort in scope compared to a more general solution. Is Box2D, or any physics package, out of what we build and ship with such a Cocos2D static lib?

[web [iPhone msg]]

**Comment by vlidholt** [comment]
The cocos2d-ios.xcodeproj and cocos2d-osx.xcodeproj already builds to a static library. I think that the best way (currently) to include Cocos2d in your project is as a sub-project. It will allow you to modify the source very easily, and if you do not touch the source you can just replace the complete sub-project folder and Cocos2d gets updated. I think that this is how the templates should look too.

About adding stricter warnings for the compiler, that can be a good idea. But imho it's never good to hide warnings with #pragma statements. Also, for outputting header files to go with the static library there is a 'copy header' phase in Xcode's build settings that should be used for this purpose (if we need to have stand-alone lib, this feature would be the correct one to use).

**Comment by slembcke** [comment]
Subproject:
pro - Separate compiler settings.
pro - Can still edit and browse Cocos2D source code.
pro - Would make updating the lib easier. Just drop in a new cocos2d/ directory and it should mostly "just work".
pro - Works well as a separate git repository or submodule. Would make it easier to share Cocos2D fixes or changes.
con - Makes a big mess of the parent project's targets list: http://files.slembcke.net/upshot/upshot_91jewA6R.png

Target:
pro - Separate compiler settings.
pro - Can still edit and browse Cocos2D source code.
pro - Keeps the target list simple(r).
con - Upgrading is more work and may require adding/removing files by hand.

Static Lib:
pro - Easier to distribute.
pro - Easy to upgrade. Just need to replace a directory.
pro - Makes no mess of the targets list.
pro - No complaints about new warnings when Xcode defaults change.
con - Can't edit or browse the Cocos2D code.

Source Files:
pro - Can edit and browse Cocos2D code.
pro - Doesn't make a mess in the targets list.
con - Upgrading may require adding/removing files by hand.
con - No separation of compiler settings.

Not exactly exhaustive. I think either a subproject or target is ok, we might want to make a separate project file to clean up all the unnecessary targets if we go that route though.

**Comment by Panajev** [comment]
Thank you for an exhaustive response, I will give myself time to properly address this topic, but I wanted to make a few points clearer.

I agree that perhaps reorganizing the project this way is not liked by many, but it is not necessarily a must have of what I was proposing. I am more than happy to bring back the older project structure. The copy header files phase should be good enough.

In addition to the points made by Scott, I wanted to add a few thoughts.
I think that a third party framework such as Cocos2D should not think of its users necessarily as potential maintainers of the framework itself and this is beside the point of whether they could do it or not. 
A framework should be easy to add to a project, easy to version/point the blame when it breaks (v4.x.y broke this and that for example), easy to upgrade, and it should not burden the target application everyone you clean your project and recompile. 

This is an open source framework, so it is part of its appeal that it is relatively easy to check out its code, modify it, re-build the static library, and update a project that uses it. This IMHO does not mean that projects using Cocos2D should carry the whole source of the project or the repo as submodule in their own application.

I did add the pragmas to make it compile where the solution to the problem required quite a bit of refactoring that should be at least agreed upon. They do also serve to highlight issues which we need to address. I am fine with taking them off and not have the whole project compile until we fix them all, although a few are somewhat Apple's bugs, and others are stylistic choices by Cocos2D in the past years. Apple is moving away from ivars and pushing properties much more aggressively, so this should be looked at too.

[web [iPhone msg]]

**Comment by Birkemose** [comment]
As far as I know, setting up the install script, is a matter of editing the current files, so that they represent the changes. Setting up new project templates should be equally easy, so I would suggest a cocos2d-v3 template, and a cocos2d-v3-static template. Personally I do not fancy a static lib, where I can not browse the code.
The file templates are as far as I know, the hardest ones to get to work.

**Comment by Panajev** [comment]
Sorry, e-mail was fired off before it had been finished or some of its spelling mistakes corrected.

I quoted the iVars issue as a warning, generated by activated the -Weverything flag IIRC, that requires a quite invasive change that needed more discussion. In other cases it was a pervasive use of floating point comparisons in quite a lot of key parts of the code, but there were a lot of warnings fixed by changes in the pull request. 

I think the warnings activated in the pull request are the minimum amount of warnings I would like to use in a project and warnings should be treated as errors.

Biker, I think it is fair that some users might want to go over the source code of Cocos2D, but I still think that as an engine/framework matures less and less programmers developing applications with it should need to keep poking at and/or modifying the engine's source code.

[web [iPhone msg]]

**Comment by vlidholt** [comment]
Another big disadvantage with distributing Cocos2d as static library is that it will not compile out of the box with Apportable. Easy cross-platform abilities will be a great selling point for Cocos2d-iPhone in the future and something many developers take into consideration when choosing a framework for development.

**Comment by orionnoir** [comment]
Just a peanut in the gallery here, I can think of only one app (out of five) that we've published in the last few years that has not tweaked the cocos2d source to bend it to our will (or to serve our bad design, but that is another story.)

**Comment by vlidholt** [comment]
@orionnoir I think this is one of Cocos2d's largest strengths – that it can be modified and tweaked to work the way you want. Although, doing so makes the upgrade path harder.

**Comment by slembcke** [comment]
Oh, that's a good point. I hadn't considered that. Providing static libs for Apportable is certainly possible, but what a pain.

I guess I don't feel that modifying the source is bad form at all. A lot of times libraries simply don't work the way you need them to. This is occasionally very frustrating with Unity and requires awkward workarounds. Having ported some (other people's) Cocos2D games to Android using Apportable, being able to modify the Cocos source was absolutely vital.

**Comment by Panajev** [comment]
App Portable is a very good point, but it portability was the order of the day we would be doubling down on the JavaScript efforts started in v2.x and not taking them out.
Still, I will modify the structure of the project back to what it was and resubmit the pull request.

Anyways, especially for small indie projects, people want to push both their app and the engine in a particular way so they might want to modify both, which is not something barred by distributing the static library because the project is open source and easily embeddable as is.

In larger organizations, you still want to keep engine and tools team on the engine/framework and the games people on their respective areas of expertise and well focus more on the task that concerns them. Shipping the library out to the games/client teams is much preferable as it makes support much easier.
Supporting people using the library and not thousands of forks is also a point worth considering IMHO.

[web [iPhone msg]]

**Comment by dominik-hadl** [comment]
I've looked inside the templates and fixed 99% file problems - the basic cocos2d (iOS) template almost works.
Only problem I found is the Chipmunk library, where I have to figure out how can I add it as a target dependency inside the template.

If you don't mind, I'm willing to fix and update all those templates (right after I finish a project I'm working on) :)

**Comment by Panajev** [comment]
As I said, I moved back to the old project's structure, fixed all the
compilation errors I managed to trigger :), merged with the latest changes
in develop-v3, improved the scripts building ready to use packages for iOS
and OS X, and updated the pull request:
https://github.com/cocos2d/cocos2d-iphone/pull/340

Sorry for partially hijacking this thread, let's move the discussion there,
but let's discuss about it more. I hope I do not have missed some key
workspace/project setting when I resolved the merge conflicts compared to
some other project changes made recently (it should be easy to re-add if
needed), but I tried my best not to do so and bring a good quality pull
request to the table. I think it does improve the project's foundations for
the future and it is better to take a look at it now that the project is
finalizing where it is aiming rather than months from now.
