### ISSUE TITLE
Audio library needs to be added

### ISSUE THREAD

**Issue by vlidholt** [cocos2d/cocos2d-objc#352]
Should we still use CocosDenshion or move to ObjectAL? Pros/cons?

ObjectAL seems pretty well maintained and supports ARC. http://kstenerud.github.io/ObjectAL-for-iPhone/

**Comment by slembcke** [comment]
How does CocosDension not support ARC? I've used it in several ARC projects.

**Comment by vlidholt** [comment]
It's written in non-arc, but you are right it is possible to either include it as a static lib or have different settings for the files. It may make it slightly harder to setup a new project though (if you don't use the templates).

**Comment by slembcke** [comment]
IMO, it really should be compiled into a static library. I think it may have been a mistake to convert Cocos2D to ARC. There are already some unsolved issues with the caches since you can't make NSDictionaries with weak values. There has been a warning floating around for that for months now. In CCPhysics it would have been useful to log warnings when retaining CCPhysicsCollisionPair objects, but I can't without setting a per-file -fno-objc-arc flag. Writing libraries using ARC is problematic since it takes away a lot of flexibility.

If somebody is setting up a new project without templates, they should still be encouraged to make separate targets or use a pre-compiled static lib due to differences in compiler flags. Putting all code into a single target is just not a good idea.

**Comment by slembcke** [comment]
It's worth noting that the weak NSDictionary problem was solved in iOS 6+ by providing NSHashTable, but are we dropping support for 5.x? (Seems a bit extreme) The other options are to go back to MRC (at least for the files that need it), or write our own weak hash table.

**Comment by Birkemose** [comment]
I see no reason not to continue to include CocosDenshion, as long as it is mentioned that the API has been abandoned.
I have recently looked into the amazing audio engine, which is very cool.

**Comment by vlidholt** [comment]
Lars, are you saying that we should include both CocosDenshion and ObjectAL?

I say that the biggest advantage ObjectAL has over CocosDenshion is that it is maintained, and it has some more features (reverb etc). The only disadvantage that I can see is that current examples are for CocosDenshion (although playing background music and effects are very similar in both engines and only takes a few lines of code).

**Comment by dominik-hadl** [comment]
I've used both of them number of times and I have to say, that OpenAL is the way to go. IMO I would remove CocosDenshion and use ObjectAL or similar, for example the Amazing Audio Engine (both are great).

The reason why I say so is, that if you try to do something above normal (playing 10+ sounds very fast, multiple background music tracks etc.), CocosDenshion won't be accurate enough, will damage the audio sometimes and even crashes all audio playback in app (app needs restart after this).

Not to mention, that CocosDenshion doesn't support any of the basic SFX, like reverbs, hall/echo and more.

So, my vote is:
**+1 to OpenAL based audio engine**

**Comment by davilca** [comment]
+1 to @nickskull 
+1 to ObjectAL

To me, as a game developer and a cocos2d user, what @nickskull says (playing 10+ sounds very fast, multiple background music tracks etc.) is not above normal, is NORMAL in game development, sooner or later.

So, ObjectAL is the way to go, from my own experience using both audio systems. And it could be a static library because there is no much to tweak or hack.

Cheers!

**Comment by FramusRock** [comment]
I have used all four of them (ObjectAL, CocosDenshion, the Amazing Audio Engine and FMOD) extensively.

My testing results were that AAE is very likely to have audio crackles / glitches when there are many sounds at the same time / fired fast after another. I even talked to the developer of it (since I wanted to support Audiobus in my app and use AAE). He said that AAE is not made for that. It's not made for playing sound effects at a fast rate nor for layering sounds - which is what we need for games. 

CocosDenshion and ObjectAL are both really good for that purpose.
@nickskull Yes OpenAL is the way to go - I think so, too. But AAE is not based on OpenAL. It's an engine based on CoreAudio which is basically made to promote Audiobus (since it's easy to plug Audiobus in it).

I know FMOD is commercial but it is by far the best AudioEngine I've ever seen. It can do anything you want. You can define custom latency, amount of sounds you need at the same time, tons of DSP effects, etc. Playing a lot of sounds very very fast is absolutely no problem for it. 

For cocos2d I'd suggest using ObjectAL. It is ahead of Denshion and based on OpenAL.

**Comment by dominik-hadl** [comment]
@FramusRock Oh yes, you're right - I wanted to write FMOD instead of AAE. 

FMOD is really cool, however the pricing is absolutely insane even for indie developers.

**Comment by vlidholt** [comment]
Fixed, moved to ObjectAl for audio
