### ISSUE TITLE
Fix optimizations in CCTiledMapLayer

### ISSUE THREAD

**Issue by vlidholt** [cocos2d/cocos2d-objc#368]
Uses strings and names, this must be replaced by more efficient code. (See warning on CCTiledMapLayer)

**Comment by cocojoe** [comment]
I've been doing some benchmarks on a clean 100x100 (10K tiles) isometric map, during the atlasIndexForExistantZ method against all 10K tiles, which currently implements Fast Enumeration takes ~280ms.  Replacing with a NSArray binary search (iOS4+) it executes in 14ms.  

So nice 20x gain on that, will commit that in today.

**Comment by cocojoe** [comment]
I've reviewed the other potential performance warning after fixing TileMap issues in #397 , all profiling was on an iPhone 4.  The real bottleneck was the old code refactored above.

I am benchmarking by looping tileAt for all tiles in the map.

A full 25x25 (625 tiles) map takes 1 ms for 1st run.
A full 100x100 (10,000 tiles) map takes 21 ms for 1st run, subsequent runs takes 8 ms as at this point the lookup is now being performed using the internal int array rather than having to lookup Node name.

This can be closed.
