### ISSUE TITLE
[CRITICAL] GitHub file size limits

### ISSUE THREAD

**Issue by lhunath** [cocos2d/cocos2d-objc#373]
So it looks like we've included files in the tree that are huge.  Not only are they huge, they're too big for GitHub.  GitHub has recently implemented a maximum file size limit.  As a result, the cocos2d-iphone repo is now no longer forkable and any forks can no longer push changes.  This effectively breaks the repo for any contributors:

remote: warning: File external/spidermonkey/mac/lib/libjs_static.a is 87.42 MB; this is larger than GitHub's recommended maximum file size of 50 MB
remote: warning: File external/spidermonkey/mac/lib/libjs_static.a is 86.01 MB; this is larger than GitHub's recommended maximum file size of 50 MB
remote: error: GH001: Large files detected.
remote: error: Trace: bfc4941847108928187533291172e457
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File external/JavaScript/SpiderMonkey/osx/lib/libjs_static.a is 193.05 MB; this exceeds GitHub's file size limit of 100 MB
remote: error: File external/spidermonkey/iOS/lib/libjs_static.a is 151.38 MB; this exceeds GitHub's file size limit of 100 MB
remote: error: File external/spidermonkey/iOS/lib/libjs_static.a is 136.30 MB; this exceeds GitHub's file size limit of 100 MB
To git@github.com:lhunath/cocos2d-iphone.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@github.com:lhunath/cocos2d-iphone.git'

The only decent solution involves removing these files from the history by rewriting.  This is really bad news for any forks that have already got these changes; but the longer we wait, the worse it will get for everyone.

**Comment by orionnoir** [comment]
If it comes to a head there are options. I currently use BitBucket (3+ years now) and have had decent success in their space. For those that have not used a system like it they may be daunting, I found the rewards far outweigh the limitations/learning curve in time (I am not saying there was not pain.) There are a lot of similarities too so its not to far a stretch. I don't know if the other differences in the account capabilities/limitations make a difference.

http://stackoverflow.com/questions/6315528/how-much-space-can-your-bitbucket-account-have

**Comment by dominik-hadl** [comment]
If I had to do the call, then I would probably remove all this JS shit, as I don't think people use it and if they do - then just add a new section to the readme where they can download it or we could create a submodule for something that is needed and is very big.

**Comment by lhunath** [comment]
Well, the JS stuff should definitely be optional (which I believe it is), since few games will actually want to just tack on an extra 150MB to their download size for just a static lib.

I'm also unsure of the logic in including external dependencies in the source tree.  It seems cocos2d is doing this for a lot of things and I think these external deps should all be in their own repo.  I think libs should be compiled from source, not included as binary.

**Comment by lhunath** [comment]
At lhunath/cocos2d-iphone I've pruned spidermonkey's external dependency with:

```
git filter-branch --index-filter 'git rm -r --cached --ignore-unmatch external/JavaScript/SpiderMonkey external/spidermonkey' HEAD
```

**Comment by Birkemose** [comment]
@lhunath, allow me to quote your reply to me

/quote
In the issue I propose filter-branch and removing the offending files. It’s extreme, because it rewrites history which will be invasive for all that follow the repo. But seeing as the offending files are somewhat deep into the history, it’s the only way to make the repo healthy.

But actually, I think this is a good time to think about what caused this: External dependencies in the tree. I think external dependencies should exist outside the tree and be maintained either via git submodules or something like cocoapods. Also, I’d avoid binary dependencies and instead compile them from source the same way cocos2d is compiled from source.

If it were up to me, I’d filter-branch all the external dependencies away. It’ll be a bit of work to the repo set up to do dependency handling well, but it’ll certainly future-proof us.
/un-quote

Thanks for the input on this. I will see if I can spend some time with it start next week, and hopefully get it fixed.

**Comment by Birkemose** [comment]
Do we have a black belt git user, who can do what @Ihunath suggests, or maybe come up with a better solution. I am afraid it is a bit beyond me.
