### ISSUE TITLE
CCSprite9Slice dirty flag

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#374]
Dirty flag does not work. Initial rendering is not always done. Check CCButton

**Comment by vlidholt** [comment]
Not super important to fix, but what is the status on this?

**Comment by Birkemose** [comment]
Will check up on it

**Comment by slembcke** [comment]
In the 3.1 rendering code I've removed the dirty flag completely. It looked like there might be some cases where it didn't get update correctly, and I remember there being a GitHub issue about it.

Right now it just recalculates the mesh completely each frame. I haven't bothered to verify it yet, but it's still probably considerably faster than the existing version since it removes at least 2 draw calls and opens the possibility of batching.

If it's not a priority to fix this for 3.0 it will go away with 3.1.

**Comment by slembcke** [comment]
Doesn't seem like anybody is jumping at the opportunity to fix this in 3.0, and it hasn't come up in the forums at all. I'm going to close this.
