### ISSUE TITLE
Chipmunk ARC

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#375]
I see 3 options
1) Convert Chipmunk to ARC
2) Include as a static lib ( some will miss the source code )
3) Try to get script to add -fno-objc-arc to the Chipmunk files

**Comment by dominik-hadl** [comment]
**Option 1** has only positives, if we are not talking about someone who has to convert it. It is 90% of removing release/retain/autorelease, however there are some issues with objects in structs et cetera. If someone skilled in memory management could do that, I think that is the best option.

**Option 2** has a problem when installing templates - if system of a user is modified and default paths to stuff are changed, then xcodebuild from commandline fails. Maybe could be solved in install script. But it still has no source files... meaning no editing.  

**Option 3** very hacky, not good solution. I've just created a quick script (for Chipmunk):

```
PROJ_FILE="${PROJECT_FILE_PATH}/project.pbxproj"
SRCH_ARR=("ChipmunkConstraint" "ChipmunkSpace" "ChipmunkBody" "ChipmunkShape" "ChipmunkMultiGrab" "CocosDenshion" "SimpleAudioEngine" "CDXPropertyModifierAction" "CDAudioManager")
for i in ${SRCH_ARR[@]}; do
    CUR_SRCH="\* ${i}.m \*\/"
    STR_RPLC="\* ${i}.m *\/; settings = {COMPILER_FLAGS = \"-fno-objc-arc\"; };"
    echo "$STR_RPLC"
    sed -i "" "s|$CUR_SRCH;|${STR_RPLC}|g" "$PROJ_FILE"
done
exit 0
```

This has to be added as a first build phase and it could even be added in the templates. This script could also delete itself after it is run, however if any modification to the project file is made, it will cancel the build (at least for the first time) and all expanded folders in Xcode close - so not very nice solution.

Just my two cents :)

**Comment by slembcke** [comment]
Again, to be blunt, I don't think changing Objective-Chipmunk to use ARC makes any sense since it interacts so much with C code. While it could be done, but I really don't like using ARC in non-pure ObjC code.

In my opinion, the Objective-Chipmunk (and other libraries too) should be in their own separate targets or subprojects. Dumping everything together with the same compiler settings isn't a very good idea and has been a problematic part of Cocos2D's templates for years. I always end up reorganizing my projects with separate targets anyway.

A subproject has a couple of benefits, but the simplest solution would just be to include Chipmunk source files and have them go in their own target.

There was some discussion about this is the past also:
https://github.com/cocos2d/cocos2d-iphone/issues/350

**Comment by dominik-hadl** [comment]
Oh, you're right. I forgot about the option to create a separate target in the same project that would compile Chipmunk to static library. Yeah, that is feasible also with the templates. Then **Option 2** is probably the best option. Should I do it that way then?

**Comment by Birkemose** [comment]
Maybe we should get our feet wet, and try adding chipmunk as a subproject?

**Comment by dominik-hadl** [comment]
Just to clarify - it's not possible with the templates to add a subproject - only option is to add multiple targets. I will do that someday next week and we'll see if that's the way to go.

**Comment by slembcke** [comment]
The templates have Chipmunk as a subproject now. Is there anything else to do or can we close the issue?

**Comment by dominik-hadl** [comment]
I think we can close this :)
