### ISSUE TITLE
Xcode Templates improvements

### ISSUE THREAD

**Issue by dominik-hadl** [cocos2d/cocos2d-objc#386]
Things to improve in Xcode Templates and the install script.
- [x] **Change Chipmunk to be compiled in the templates, rather then pre-compiled**  
     This means adding a new target in the template and make the main one to have Chipmunk as a target dependency. (**Note:** _Only possible to add in Other linker flags._)  
- [ ] **Auto-generate templates depending on changes in cocos2d files**  
    Means adding a new target to the main cocos2d iOS and Mac project, which will generate the required .plist files. Also, new template generation script is needed, but could be based on the old one.  
- [ ] **Add new template with cocos2d as a static library**  
    Some people complained about not having this option and it could be done, so I will probably add this as a new Xcode template project.

**Comment by davilca** [comment]
The first one is a must have for the next release, in my opinion.

**Comment by dominik-hadl** [comment]
The first is one is now done. I will think of what I can do with the third one, but as I see it now there are only two options - either downloading a compiled static lib from the repo (or somewhere else) during the templates installation or compile it while installing the templates (this can bring some errors, if some paths are modified...). I think the best way would be the former.

**Comment by slembcke** [comment]
I'm going to bring this up again since it has been relevant again lately. There were a number of new files changed and added for 3.1 and updating the templates is a bit of a pain. I ended up half scripting it using IRB. If I need to update the templates again, I probably will end up making a proper script for it.

While Xcode templates are convenient since Xcode will show them when creating new projects, they are not well documented, difficult to maintain, and missing a lot of features for making user's lives easier (submodules, subprojects, etc).

More recent suggestions have been some variation of archiving a template and making a script to do a find/replace to rename the project. We could possibly wrap that in a GUI like the installer script.
