### ISSUE TITLE
CCLabelAtlas still required?

### ISSUE THREAD

**Issue by cocojoe** [cocos2d/cocos2d-objc#387]
Is anyone using CCLabelAtlas, it seems like legacy and personally I have only used the more flexible CCLabelBMFont.

Anyone be upset if this was retired from v3?

**Comment by dominik-hadl** [comment]
I am not using it, actually never used it.

**Comment by vlidholt** [comment]
So, this was my first though on it too. The use it has is that it's easy to create a custom mono-spaced typeface from an image. If we add this feature to CCLabelBMFont I'd be more than happy to scrap it!

**Comment by Birkemose** [comment]
+1 for adding the functionality to BM font, and scrapping atlas.

**Comment by slembcke** [comment]
CCLabelAtlas was the one thing that I didn't bother to fix with the contentScale changes since there was talk of removing it. It's still used by the fps stats label, and it renders incorrectly in some cases. SpriteBuilder also still uses the atlas labels for a couple things, but we could either copy the code into SB or fix it pretty easily.

Does anybody want to take this issue on? Perhaps more importantly, dose anybody have any atlas based fonts we can use for testing?

**Comment by vlidholt** [comment]
Maybe we should just make this a private class. I.e. remove it from the cocos2d.h file?

**Comment by cocojoe** [comment]
Could do, I was thinking about just depreciating the class.

On 18 December 2013 07:07, Viktor Lidholt notifications@github.com wrote:

> Maybe we should just make this a private class. I.e. remove it from the
> cocos2d.h file?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/387#issuecomment-30821231
> .

## 

Martin

**Comment by vlidholt** [comment]
This is made private, I'm closing this.
