### ISSUE TITLE
CCLayer class renaming

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#404]
CCLayer should be renamed to ex CCSpriteSolid
CCNodeMultiplex should probably be placed in a separate file 

Class renaming
CCLayerColor -> CCSpriteSolid
CCLayerGradient -> CCSpriteGradient

**Comment by vlidholt** [comment]
To me the name 'sprite' implies something that has an image/texture attached. CCSpriteSolid sound like a sprite that doesn't have alpha or something. I think the old names for these work.

**Comment by slembcke** [comment]
Hmm. On the one hand I think the new names would make the classes easier to find by auto-completion. I do know a lot of people that learn exclusively by what their IDE tells them. To find CCLayerColor you'd have to know to type "CCL" at least. On the other hand, "sprite" does imply a bitmap though I don't really think anyone would be confused by what the solid/gradient ones did once they saw their init methods.

I'm leaning slightly to the CCSpriteSolid CCSpriteGradient side, but I'm not really sure it matters.

**Comment by dominik-hadl** [comment]
+1 for naming it CCSprite. To me, sprite is something that I can see on the screen and that could also be solids and gradients.

**Comment by Birkemose** [comment]
Seems none of the names are really good, so Scott's point about auto-completion, is probably the best to aim for.
CCColored... something?

**Comment by slembcke** [comment]
Oh, so that's why I was leaning towards CCSpriteGradient, CCSpriteSolid. You can't do anything useful in Cocos2D without knowing about CCSprite, so you are more or less guaranteed that they will know about that. Naming the other classes with the same prefix will make the solid/gradient version show up as related classes in their auto-complete.

Though a stronger argument against it might be that the solid/gradient types are not actually subclasses of CCSprite and won't have some of the same methods. The best alternate names I can think of are CCNodeColored and CCNodeGradient. They are still prefixed with something common that way.

**Comment by andykorth** [comment]
I do like the idea of starting with CCColored..., CCColoredNode, CCSolidColor (CCGradientColor) is okay, but it sounds like a representation of a color, not something drawn to the world. I'm not too opposed to CCSpriteSolid, even though they aren't bitmaps... 

CCColorNode / CCGradientNode is kind of growing on me. There's plenty of other CCNodes that end with the word "Node", so it doesn't seem out of place. It helps differenciate from a ccColor. (CCDrawNode, CCSpriteBatchNode, even CCParallaxNode)

I think it's definitely good to remove the world Layer, since once had a specific meaning that we've moved away from.

**Comment by billhollings** [comment]
Hmmm...CCLayer is currently the superclass of CC3Layer, which is a where a 3D camera presents is scene.

Certainly calling it something related to "sprite" is not really appropriate as a superclass of an entire 3D scene ! :^)

Can someone explain to me what the conceptual meaning of what _was_ CCLayer is now? It was just a CCNode that responded to touches. What is it now?

Should I be expecting to use something else as the parent of CC3Layer now?

**Comment by slembcke** [comment]
Oh... So you probably missed that from a couple months ago. CCLayer is gone. It's original purpose was to handle user input, and that was rewritten to be more UIResponder-like and can be done with any CCNode. CCLayer no longer served any purpose. That's why it's subclasses are being renamed since there is no longer anything named CCLayer.

I suppose your CC3Layer would just become a CC3Node too?

**Comment by billhollings** [comment]
Ah...yes...out of the loop...as usual. :^)

Okay...so CCSpriteSolid & CCSpriteSolid are now direct subclasses of CCNode?

And you're suggesting that CC3Layer should also be a direct subclass of CCNode as well?

Does CCScene still exist? Is the assembly structure a CCScene holding onto a bunch of various CCNodes? With no intervening CCLayer to marshal events?

**Comment by Birkemose** [comment]
I actually also like CCColorNode, CCGradientNode, as this is in line with other node naming, and still a logic choice when looking for a coloured quad.
CCLayerMultiplex, which was renamed to CCNodeMultiplex, should then become CCMultiplexNode.

Consider it done ...

**Comment by cocojoe** [comment]
I can see the argument for the node related names however from the end user perspective I think that CCSpriteSolid, CCSpriteGradient have the best flow.  

It will work well for discovery given how common CCSprite usage is, many times when I've been prototyping I've just wanted a quick solid colour sprite that I could later replace with a textured sprite.

**Comment by vlidholt** [comment]
I think that naming it CCSpriteSolid, indicates that it is a kind of sprite (i.e. a subclass) which is not the case. The points with autocompletion make sense to me though. I my favorite naming so far is CCNodeColor and CCNodeGradient. We just renamed all action classes CCActionSomething, undoing this scheme would be a step back. Alternatively I'm good with keeping the old names, which I think are descriptive and works.

**Comment by Birkemose** [comment]
CCNodeColor etc it is then

**Comment by davilca** [comment]
Maybe late to the party, but I would prefer CCNodeColor and CCNodeGradient if those classes won't inherit from CCSprite and won't have a texture attached.

**Comment by cocojoe** [comment]
The implied inheritance issue is fair enough so happy with CCNodeColor, CCNodeGradient.   It's a shame Color is never spelt correctly ;-)

**Comment by vlidholt** [comment]
This appears to have been implemented. Closing the issue.
