### ISSUE TITLE
Default resolutions and CCAppDelegate class

### ISSUE THREAD

**Issue by vlidholt** [cocos2d/cocos2d-objc#413]
Currently the AppDelegate class is somewhat complicated, with lots and lots of options for setting up the CCDirector and GLView. I suggest that we create a CCAppDelegate class that contains all code that generally will not be modified by the user and let the user create a sub-class of that class for the configuration. We should also provide a simplified setup method.

By default, only the application:didFinishLaunchingWithOptions: method would be needed to be overridden. It could look something along these lines:

``` objc
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    [self configureCocos2dWithPixelFormat: kEAGLColorFormatRGB565 screenMode:CCScreenModeFlexible animationInterval:1.0/60];
}
```

If power users really want to tweak the settings they can just implement the configure method themselves and do whatever they need there.

I'm thinking that we could provide two default 'screen modes', flexible and letter boxed. Flexible is the current default and a letter boxed screen mode would give developers a fixed logical coordinate system that will be scaled to fill the screen but crop off edges on some devices to keep the square aspect ratio.

I suggest that for the fixed size we use a logical coordinate space of 568 x 384 points. This may seem arbitrary, but would make it easy to do letter boxing on all iOS devices while keeping the 1x, 2x and 4x scaling (see picture below).

![resolutions](https://f.cloud.github.com/assets/1539812/1686740/a9146202-5deb-11e3-8aeb-b12c6fc9d97a.png)

**Comment by dominik-hadl** [comment]
That's exactly what I was talking about in another thread - I would really like to see the app delegate setup a lot simplified (although I will probably override it each time :D). I just remember that when I first saw all the settings I was a little scared and wasn't sure what is all that code in there, so I think that newbies would be happy if it was easier to set it up.

**Comment by cocojoe** [comment]
I like the idea of facade for this as there is rarely much for the average user to change, in recent memory I think the changes had been related to rotation compatibility in iOS6 , at least this way it would have been easy to roll out the fix.

**Comment by Panajev** [comment]
The fixed resolution mode sounds nice, but it should allow the user to optionally set a frame texture... See Pocket Frogs on iPhone and iPad.

[web [iPhone msg]]

**Comment by davilca** [comment]
Hello!

I don't think that cropping the game is a good idea because you will hide playable area (even enemies, HUD, or whatever), so you must take that into account when designing the game. Does anyone here want his game to be cropped on other devices? Just asking. Anyway, I suppose that's one option (the "fixed" one). Having different options is good. But, in my opinion, it should be just the contrary: adapt the game to the screen, keeping the aspect ratio (the "flexible" option).

The easy setup method is a good idea, although I like to read the config code to understand a bit what's going on. I make pixel art projects, so I usually change some more stuff, like disabling retina display, enabling depth buffer to use vertexZ, change magnification filter, disable subpixel, etc. What about having different preset config functions? One function to config default games, other funtion to setup pixel art games, and another function to config 3D games. Well, these could be templates also.

**Comment by slembcke** [comment]
Yeah, I had some notes about the same idea in an old Google doc. It's all pretty easy to do just by changing the GL view's frame bounds. 

I'm not sold on the idea of a built in "fixed size" though. I agree with @davilca that cropping as the only option seems problematic. Maybe it makes sense to have both the cropped version and a bordered version? (I think @Panajev was getting at this too?) Some games will tolerate cropping like side scrollers, and some will tolerate a border nicely like single screen puzzle games.

**Comment by slembcke** [comment]
Hmm. Actually, thinking about this more...

I've made a couple of non-scrolling games with borders on ipad, though only the gameplay itself was bordered. The reason was because the levels themselves couldn't be resized, and rescaling them slightly would have looked bad. The other scenes (menu, options, etc) were natively sized though. The border texture was drawn within Cocos2D and also set on a per-level  basis to match the contents. Thinking back on it, I'm not sure if insetting the GL view would have worked very well. Adding borders in Cocos2D code is pretty easy anyway. So I think I take back the bordered GL view idea...

Having the cropping mode built in still seems fine as long as it's not the default.

**Comment by vlidholt** [comment]
If you are doing the cropping mode, it should be easy enough to add the border (just add it outside the 'safe zone').

**Comment by vlidholt** [comment]
I've added the base structure for this. Decided to save all configurations in a NSDictionary passed to a method named `- (void) setupCocos2dWithOptions:(NSDictionary*)config`. The advantage of using a dictionary is that we can add more options in the future without changing the API and also it will be trivial to add configuration details in a plist-file that could be generated by editors such as SpriteBuilder.

The only method the users needs to implement in their AppDelegates now is `- (CCScene*) startScene` which should return the first scene Cocos2d should display. For more advance users, they still have the option to override any other behavior of the CCAppDelegate.

I have not yet fully implemented the screen mode setting. Also, we may want to add a configuration option for the CCFileUtils here (use the traditional suffixes or use directories).

**Comment by slembcke** [comment]
Looks good.

I think the one thing that I would change is to push the application:didFinishLaunchingWithOptions: method to the user delegate instead of CCAppDelegate for two reasons. I've never written an app where I didn't have some non-Cocos init code in didFinishLaunching for analytics, NSUserDefaults, etc. Secondly, it also makes it obvious that there are additional setup options available, and lets them find where the setup happens if they want to modify it. Since it's only a two line method, It's not going to be a scary wall of code like the old app delegate.

**Comment by vlidholt** [comment]
Make sense, I'll do that change!

**Comment by slembcke** [comment]
The method is called setupCocos2dWithOptions:, but all of the dictionary keys have names starting with CCConfig_. Mind If I change them to be CCSetup_ instead?

Was about to implement the fixed size option, but a potential problem occurred to me. While we can have it set up a custom projection that performs the clipping correctly, what should [CCDirector viewSize] return? Returning the fixed resolution size (568 x 384) would requires some pretty nasty hacks since its used for so many different things.

**Comment by vlidholt** [comment]
CCSetup\* may be a better name.

Good question about the viewSize. Not exactly sure where it is used. I think it could return the actual viewSize (in points?) and if we set the contentSize of the CCScene correctly it should work. Which are the problem points for the viewSize method?

**Comment by slembcke** [comment]
CCDirector.viewSize is used within CCDirector related code pretty extensively to mean the actual UIKit size. There are quite a few places where it's used for default node sizing though too. There are a smattering of uses like below in various node classes and even the CCBReader code. When using the fixed size mode, what they really want is the projection size and not the GL view's size.

```
-(id) init
{
    CGSize s = [[CCDirector sharedDirector] viewSize];
    return [self initWithColor:ccc4(0,0,0,0) width:s.width height:s.height];
}
```

**Comment by slembcke** [comment]
I think @vlidholt was pretty happy with how testing went with this. Is there anything else or can we close this issue?

**Comment by vlidholt** [comment]
Closing this now!
