### ISSUE TITLE
CCNode's getChildByName is not recursive

### ISSUE THREAD

**Issue by andykorth** [cocos2d/cocos2d-objc#414]
I sure expected it to be. Especially if people are using it inside big hierarchies to find objects they are tracking by strings.

Alternatively, there could also be a recursive version.

Any thoughts?

**Comment by vlidholt** [comment]
The reason I didn't implement it recursively was that the getChildByTag wasn't recursive. But, I think it's can be reasonable to expect it to be.

**Comment by dominik-hadl** [comment]
Or there could be a `getChildByTag:(int)tag recursively:(bool)isRecursive` and similar for searching by name. At least that's what I did in few of my extensions.

**Comment by slembcke** [comment]
Hmm. I was on the fence about it. Looking at the docs for the similar GameObject.Find() method in Unity I found this:
"This function is most useful to automatically connect references to other objects at load time (...)"

I usually avoid using that feature in Unity since it's so easy to make bugs by simple misspellings of strings scattered around the project. I guess I do use it to find child objects in things that I instantiate, and that's a use case that will carry over to SpriteBuilder pretty well I think. So I guess I would say making it recursive makes sense.

Unity also lets you use a path-like string too. ex: "ship/thruster1". That might be something to consider for the future, but it's not really a trivial feature to add.

**Comment by andykorth** [comment]
I like `getChildByTag:(int)tag recursively:(bool)isRecursive` more than having two versions of the method, since no one will ever use the wrong one accidentally. And most importantly, it clears up incorrect assumptions, like the one I had. I don't have a huge preference other than that.

**Comment by ghost** [comment]
Using more than one version is very natural for Objective-C programmers. They will definitely see both, and the amount of confusion will be at least less than `addChild:z:tag:`, since that method has 3 versions.

The reason I would push for two versions is the convenience of using methods with single arguments in objective-c. When you so a CCCallFunc, you can pass a single object, so if the method requires more than one objects, it cannot be used. The same applied to the Objective-C methods `performSelecter:`.

**Comment by vlidholt** [comment]
I like `getChildByTag:(int)tag recursively:(bool)isRecursive` too. I think that one method would be enough, Cocos2d often adds too many aliases for the same thing, which imho makes things harder to use not easier.

**Comment by andykorth** [comment]
Here's what I whipped together:

https://github.com/andykorth/cocos2d-iphone/commit/2b08f0e6587d45724fd9d0f867489e5ece2847fd

At the moment it has a recursive `getChildByTag:(int)tag recursively:(bool)isRecursive` and a `getChildByTag:(int)tag recursively:(bool)isRecursive`. I'll wait for a few more opinions before deciding if we want both. 

(Hey look, there's unit tests in there!)

**Comment by slembcke** [comment]
@vlidholt  Agreed. I feel like in many cases it's common to have many aliased methods because they were added over time. Unless the method has 5 arguments, it's a lot cleaner to have fewer methods if each one isn't trying to do too much.

**Comment by vlidholt** [comment]
@andykorth So, there was a decision made to replace the tag property by a name property, so I don't think we should reinstate the tag. In the link you sent I don't see any tags so I am happy with that! Just double check that the old method isn't used inside Cocos somewhere.

**Comment by andykorth** [comment]
Oops, I'm not sure how the word tag snuck into my github comment. Definitely names. 

I'll wrap this up today and go with one method instead of two. Thanks!

**Comment by cocojoe** [comment]
Shouldn't this have a default for existing behaviour instead of having to add 'recursively' all the time?

**Comment by slembcke** [comment]
The overall consensus from earlier in the discussion was that we should avoid adding method aliases for new methods. In this case the method wasn't completely new (tag -> name). With auto-complete, Xcode does most of the typing for you at least?
