### ISSUE TITLE
Installer + User Guide

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#432]
Maybe it is worth looking into if an installer / automator of some kind, could ease the process for newcomers? Nothing too fancy. Would be great if it could download latest version, have a version tracker of some sort, automate installation, and link to the forum (and maybe Rays site etc)

Since I did the hello world, maybe I should look into polishing that a little more for the release, and add a Users Guide to help a newcomer through the first couple of steps?

Any thoughts on this? Should a user guide be a PDF, or could it be integrated better with Xcode in some way?

**Comment by davilca** [comment]
Hello people!

For new users, an installer and a quick start guide would be fantastic, because installation of the libraries were always a little annoying. For the future of cocos2d, and in order to grow the user base, it would be better to ease the installation process.

Personally, I prefer online guides or documents, instead of Xcode integration. In fact, it would be great to clean up and start from scratch the Documentation page (http://www.cocos2d-iphone.org/wiki/doku.php/) to fit the new workflow. I suppose that most of the new users get confused there, and that's why there are some recurrent forum post from time to time.

Also, I think that newcomers miss some more examples and use cases in the documentation. The cocos2d built in example projects are ok, but you must compile and execute them to see what they do, and then investigate the code to see how they do that. Maybe a good idea is to write code examples for the most important classes, showing images of the output result if needed. Also, you could link these examples to the class reference.

I suppose all this documentation clean up should be done when the API is stable.

**Comment by cocojoe** [comment]
@Birkemose I don't think at this point we need some sort of cocos2d management application.  I think for now it would be sufficient to have a clear download section on site, with a download for cocos2d 3.0 DMG.

This could contain:
1) cocos2d installer - which would uncompress, run the install.sh and copy the new appledocs into Xcode. (I've started on this)
2) A web link to cocos2d community
3) A web link or 'getting started' PDF?

It is probably just easier to have a web link for the getting started section, this way it can always be current/updated.
A heavily documented, step by step 'hello physics world' tutorial would be good. Would be a great starting place.

It would of course be great to have a Sprite Kit style user guide but may take a bit of time to do this.

Now that chipmunk files are no longer built in the install script we can remove the requirement for CLI Xcode build tools to be installed.  
Should the chipmunk files then be include in the installer 'vs downloaded in script'?
I was also thinking to include pre compiled apple docs vs building in script (as need cli tools).

I would rather have the install 'just work' vs potential for various install issues...

On a side note, should we be stripping down the Github repo when it comes to a distribution build? How many people even look in the cocos2d directory after templates are installed? I'm thinking dump it into Downloads, after it's all installed up to user what they do with it.

**Comment by slembcke** [comment]
So to throw an idea out there. You can put either a Safari .webarchive or a .pdf file into an Xcode project and view it. Links in them even work. I've done that with a README.pdf before with some basic instructions and links. I just stuck it at the top of the Xcode project so they could see it. Adding something like that to the templates would be an easy and very visible thing to do.

I agree with @cocojoe the release packages should have everything you need in them including the Chipmunk source in the right place and the documentation prebuilt. This is what I do for Chipmunk. A direct export of the Git repository isn't always very useful as a downloadable archive if it requires a lot of extra steps that can go wrong. 

As for "updating" Cocos2D, does it make sense to take advantage of Git for this? There are any number of ways we could do this, and a lot of them bad... Maybe some instructions on how to set up the cocos2d/ directory in a user's project as a submodule that points to the official Git repository would be enough? One problem with this is the gigantic size of the current Cocos repository due to the old JS libraries in the history.

**Comment by dominik-hadl** [comment]
I really like the idea of an installer and all this. I volunteer to help with this, since I also did the install script. Unfortunately, I don't have access to a computer until Wednesday.

**Comment by dominik-hadl** [comment]
Btw. There was an issue that had a solution for the problems with the big JS files, I think it was called something like [CRITICAL]... Maybe someone should look into that?

**Comment by slembcke** [comment]
This one: https://github.com/cocos2d/cocos2d-iphone/issues/373
Does anybody know what to do about it?

**Comment by cocojoe** [comment]
I'll put an installer build up tomorrow, I was going to do it today however it seems to have a couple of permission issues now.

**Comment by dominik-hadl** [comment]
Oh, it looks like I've missed the line where you said you were working on it, I see it now... my bad. I've also started working on that, I will have a working version tomorrow also. I will finish it even if its not used (just to train myself in Mac OS X apps). Sorry about that.

**Comment by cocojoe** [comment]
Installer test http://www.visitpedro.com/buildsample/cocos2d-3.0.dmg

It will get picked up as a non signed application by system security however I think a simpler disclaimer readme in the DMG will suffice given the target audience.

There are some issues in the log but I'll fix those, they were fine when running manually on CLI.
Turns out you can't just copy the appledoc across to xcode docset directory however again I've added a build script that will be executed in the installer to do it correctly next time.

**Comment by cocojoe** [comment]
Installer update, added forum links and a basic read.me for the most likely install issues (this can be expanded). Docs are building and installing correctly. Tested in Xcode 5.0 (Need someone to test 5.0.1+) as may possibly be issues from what I've read on appledoc git.

http://www.visitpedro.com/buildsample/cocos2d-v3.0.dmg

**Comment by slembcke** [comment]
Hey. That looks really nice actually.

Some thoughts:
- The installer puts the Cocos2D source in ~/Downloads/cocos2d-v3.0. That seems a little weird to me. Do people actually need or want the source separate from the templates?
- It opens the ~/Downloads/cocos2d-v3.0 directory in the Finder, but it's not clear why. It doesn't really make it clear that it installed Xcode templates and that you'd want to use those for creating new projects. (Nobody reads the README at first)
- The install script still needs to connect to Github to get the latest Chipmunk. How hard would it be to modify the script to only download if it's not already in external/Chipmunk? Then we could package it with the downloader and skip a step.

**Comment by dominik-hadl** [comment]
I have finished an alpha version of my version of the installer. If somebody wants to have a look, it's here - https://www.dropbox.com/s/01vfrop780n5su5/cocos2d%20Installer.app.zip
(and the related repo - https://github.com/nickskull/cocos2d-installer)

It is not yet finished, still some error handling missing and there are ui bugs, but I will try to finish that today.

**Comment by cocojoe** [comment]
@slembcke heh well there wasn't an easy way to ask the user for a directory ;-)
I agree that most people probably don't actually need the cocos2d directly once everything is installed... Could just delete it upon completion.

Next installer iteration I'll drop in the chipmunk tgz at time of installer build.

I was having a think about what is the best 'next step' for the user after installation completes. I think for the average user it would be a hello world tutorial that takes them through creating their first template project.  

Once we have a nice v3 hello world tutorial I'll add a link to it in the DMG.  Should it auto-open this link as a convenience? I don't think anyone would be offended if it did.

**Comment by cocojoe** [comment]
To use simply go into the installer directory and run ./build_installer this will create a Cocos2D installer application.

For those of you who tried the original beta installer please have a look in /Users/<your username>/Library/Developer/Shared/Documentation/DocSets/ and remove any previous 3.0 installed cocos2d docsets.

Viktor can sign the installer app with Apportable's key so we will not have any OSX gatekeeper issues either :)
