### ISSUE TITLE
Node placement does not work

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#436]
Placing nodes as children of nodes, does not seem to work correctly. There seems to be issues with anchor point.

**Comment by vlidholt** [comment]
The placement of a node is relative (by default) to the parent's bottom right corner. E.g. if you place a sprite as a child to another sprite they will not be on top of each other. (This is the same behavior as with Cocos2d 2.)

**Comment by andykorth** [comment]
So I noticed that behavior when making tests. I thought that was pretty weird. It makes it tough to line up children. Children placed at 0,0 were stacking centered on the bottom left corner of their parent, for me. 

I would love to see the anchor point consistent with where the parent is placed.

**Comment by Birkemose** [comment]
This is kinda my fault, for not knowing 100% how it all works.

In previous versions, we had the option to enable or disable if anchor point was used in placement. Viktor wanted for clarity to remove this from the API, which was fine with me, because I thought the default behaviour was fine.

Problem is, that default behaviour apparently is the opposite of what makes sense to me, which leaves the API stuck in the wrong position. From a transformation pow, it does not make sense, that a child with pos 0,0, is not places at its parents position.

I think this is a major point, when building node hierarchies outside sprite builder.

Is there any way we can make this work both ways? I full acknowledge that Sprite builder needs to "do its thing", and that the old property name, ignoreAnchorPointForPosition I think it was, was an awful name.
Any way we can solve this gracefully?

**Comment by slembcke** [comment]
So I guess this comes down to the CCNode.ignoreAnchorPointForPosition property being removed. Like Andy, I've always really disliked how Cocos2D's default behavior works (though I understand why). The CCNode.ignoreAnchorPointForPosition actually did what I wanted, but the documentation on it was unclear and made it sound like it did something else. Apparently I should have been using that for years now.

Is anybody particularly opposed to adding it back. I feel like the name is really unintuitive though. Is CCNode.anchorPointIsOrigin clearer or no?

One problem that I just thought of is that CCPhysics coordinates are in regular, non-anchor point relative coords. I used this as a simplification of the API since then joint anchors and shape vertexes would be in the same coordinates as the image applied to a sprite and child sprites. It might be really confusing to use CCNode.ignoreAnchorPointForPosition and CCPhysics at the same time. I'll look into this more, but I'm a little worried.

**Comment by Birkemose** [comment]
I guess the reason why I bring this up, is, that just prior to starting working exclusively on cocos2d, I spend quite some time on sprite hierarchies with my spline lib. That would have been pretty much impossible to make, if child positioning wasn't always relative to a parents anchor point.

If you look at it from a math pow, that is the only way that makes sense.

However, if changing this, breaks sprite builder or physics, we should of course leave it as is.

**Comment by slembcke** [comment]
Unfortunately I think we've probably crossed the point of no return on this decision at about a month ago. While both CCPhysics and SpriteBuilder could be made to work a new default, there is no way we have time now. There would be a _lot_ of testing to do in a very short amount of time.

For Comparison: Unity doesn't have anchor points at all. People add extra parent nodes to things to provide the same functionality if they want it. I can't say I've ever missed anchor points in Unity. SpriteKit works the same way as Cocos does right now without any options. UIKit also works similarly, but the naming is different.

**Comment by Birkemose** [comment]
I rest my case.

**Comment by vlidholt** [comment]
For clarity to the discussion. The only thing that the ignoreAnchorpointForPosition did was to treat the anchorPoint as being (0, 0). It added absolutely no functionality, and I don't think we should bring it back. The current behavior is exactly the same as in 2.1.

That being said, first time I used this I found it confusing too, but I think it's way to late to change the behavior now and in some sort of way the current implementation actually make some sense. Not saying it's better, but may be good enough.

**Comment by slembcke** [comment]
Wait... Just did a quick test with 2.1. I'm even more confused by what ignoreAnchorPointForPosition does now:
![What?](http://files.slembcke.net/upshot/upshot_MyWZF7p9.png)

Both sprites are set up like this, only one of them doesn't have the ignoreAnchorPointForPosition property set.

```
        {
            CCSprite *sprite = [CCSprite spriteWithFile:@"grossini_dance_atlas.png" rect:CGRectMake(0,0,85,121)];
            sprite.position = ccp(568/2, 160);
            sprite.ignoreAnchorPointForPosition = TRUE;
            [self addChild:sprite];

            [sprite runAction:[CCRepeatForever actionWithAction:[CCRotateBy actionWithDuration:1.0 angle:90]]];

            CCSprite *child = [CCSprite spriteWithFile:@"grossini_dance_atlas.png" rect:CGRectMake(0,0,85,121)];
            child.scale = 0.5;
            [sprite addChild:child];
        }
```

Both sprites spin around their centers as expected, but instead of changing the node's transform so that it's relative to the anchor point it changes the overall position of the sprite instead. I am completely at a loss as to how this is useful.

**Comment by slembcke** [comment]
So here is a more enlightening screenshot perhaps with debug bounds enabled and using two different sprite images:
![Huh?](http://files.slembcke.net/upshot/upshot_uLHmtVnn.png)

The child (icon) has the ignoreAnchorPointForPosition flag set instead of the parent sprite (grossini). The effect is that it acts as though the sprite's anchor point is always (0, 0), but in a very inconsistent way. I'm really not sure how this is useful. Even looking at how it used to be used makes it very unclear why it exists.

**Comment by vlidholt** [comment]
It was not at all useful. That is why it was removed. Setting the ignoreAnchorPointForPosition pretty much only set the anchor point to (0,0) ...and yes, this was very confusing as setting the anchor point would have no effect on CCLayer where it was enabled by default.

**Comment by slembcke** [comment]
I bring this up again in relation to this thread about physics and anchor points: https://github.com/cocos2d/cocos2d-iphone/issues/471

I was considering reviving this as a fix that would make everybody happy, but it's not even an option. :(

**Comment by Birkemose** [comment]
I fixed this by adding an extra node to compound objects.
