### ISSUE TITLE
Opacity is not clamped

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#443]
Setting opacity outside the range 0-1, results in unexpected opacity.
I guess this is the same for colours.

**Comment by slembcke** [comment]
I suppose that might be confusing for newcomers. I think we should clamp the colors in the vertex shaders. Being able to use color values outside of the [0, 1] range was one of the primary reasons I thought we should move away from using fixed point colors. Otherwise the color value is useless for anything other than tinting.

**Comment by Birkemose** [comment]
Clamping in the shader makes sense. I guess default you would clamp in the vertex shader for speed, and then replace it if you needed a special case fragment shader.

**Comment by slembcke** [comment]
Right. If done in the vertex shader, the performance is almost irrelevant for 2D games.

**Comment by slembcke** [comment]
I added a clamp when converting from float to fixed point colors. That should be sufficient until/if we start using floating point color for the updated renderer.
