### ISSUE TITLE
No public API to change the fixed update rate.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#446]
CCScheduler.fixedTimeStep is inaccessible except through private headers. Need to add to add a CCDirector.fixedTimeStepInterval property to allow it to be configured.

**Comment by vlidholt** [comment]
Need to do this in a way so that we can update the implementation for 3.1 in a backwards compatible way. E.g. being able to run actions on a fixed time step too so that they can be compatible with the physics simulation. As it is slightly less efficient, I think maybe this should not be the default option.

**Comment by slembcke** [comment]
You can't turn fixed updates off, but they don't cost you any performance if you don't use them or don't know they exist. You define the fixedUpdate: methods separately from the regular update: method.

**Comment by slembcke** [comment]
Fixed. https://github.com/cocos2d/cocos2d-iphone/commit/fb645f49a6c7ba0f1f198c1d08d160ce945ae080
