### ISSUE TITLE
Anchor points

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#471]
It should be possible to build compound objects, relative to the anchor point.
As it is now, attaching a child or a piece of physics to a node, will force its placement in lower left corner. No matter the anchor point.

This is highly counter intuitive for manual placement, and will have to be changed for release.

**Comment by cocojoe** [comment]
I was just thinking this, for example:

```
projectile.physicsBody = [CCPhysicsBody bodyWithCircleOfRadius:projectile.contentSize.width/2 andCenter:ccp(projectile.contentSize.width/2,projectile.contentSize.height/2)];
```

Is ugly, the center point should be assumed to be the same position as the sprite's anchorpoint.

**Comment by slembcke** [comment]
Ugh. I really wish this would have come up a few months ago. I'm not really sure what to do now.

I do completely agree that the way that Cocos anchor points work is not intuitive at first. If it was me, I would have make the origin of a node's transform be at the anchor point instead of at the corner of the sprite, and I would have used the anchor point only to offset a sprite's geometry. Unfortunately that isn't the way Cocos has ever really worked unless you knew what the very very unintuitively named CCNode.ignoreAnchorPointForPosition property did. As it is, there is nothing else in Cocos2D that works relative to anchor points. A node's transform is used for everything in Cocos, and the anchor point changes the entire transform instead of just the rendered geometry. Children aren't positioned relative to the anchor point of their parent, rendering does not happen relative to the anchor point, input does not operate relative to the anchor point, etc. That was why I chose to have CCPhysics coordinates work consistently in the same way. This came up here too: https://github.com/cocos2d/cocos2d-iphone/issues/436

I'm not very comfortable making CCPhysics work completely differently than all of the rest of Cocos2D. Though I would have been supportive of changing how the anchor point / transform behavior works, it's so late now that it makes me very nervous. It would be a _lot_ to change and test (all of the drawing methods, SpriteBuilder and CCPhysics). I just did a quick check on what ignoreAnchorpointForPosition does, and it doesn't do at all what we had discussed (https://github.com/cocos2d/cocos2d-iphone/issues/436#issuecomment-31675943). So that's not even a quick fix that we can use.

@cocojoe
As for the code example, I've been doing the latter example like this in my examples which I feel reads fairly intuitively. "Center the shape on the anchor point" sort of thing.

```
CGFloat radius = projectile.contentSize.width/2;
projectile.physicsBody = [CCPhysicsBody bodyWithCircleOfRadius:radius andCenter:projectile.anchorPointInPoints];
```

**Comment by vlidholt** [comment]
There is no way we are changing this so close to the release. Also, I'm not convinced that having a child's coordinates being relative to a parents anchor points is the given choice. In many cases it makes more sense to have it relative the bottom left corner of the node. This is true for instance when you create layers (empty nodes with a content size), which is like a work area.

What we can do for a future release is to add a reference corner type in the position types that is relative to the anchor point instead of one of the corners.

**Comment by cocojoe** [comment]
I think end users can live with using anchorPointInPoints, so don't worry
about it :-)

On 6 January 2014 19:02, slembcke notifications@github.com wrote:

> Ugh. I really wish this would have come up a few months ago.
> 
> I do completely agree that the way that Cocos anchor points work is not
> intuitive at first. If it was me, I would have make the origin of a node's
> transform be at the anchor point instead of at the corner of the sprite,
> and I would have used the anchor point only to offset a sprite's geometry.
> Unfortunately that isn't the way Cocos has ever really worked unless you
> knew what the very very unintuitively named
> CCNode.ignoreAnchorPointForPosition property did. As it is, there is
> nothing else in Cocos2D that works relative to anchor points. A node's
> transform is used for everything in Cocos, and the anchor point changes the
> entire transform instead of just the rendered geometry. Children aren't
> positioned relative to the anchor point of their parent, rendering does not
> happen relative to the anchor point, input does not operate relative to the
> anchor point, etc. That was why I chose to have CCPhysics coordinates work
> consistently in the same way. This came up here too: #436https:%20//github.com/cocos2d/cocos2d-iphone/issues/436
> 
> I'm not very comfortable making CCPhysics work completely differently than
> all of the rest of Cocos2D. Though I would have been supportive of changing
> how the anchor point / transform behavior works, it's so late now that it
> makes me very nervous. It would be a _lot_ to change and test. I just did
> a quick check on what ignoreAnchorpointForPosition does, and it doesn't do
> at all what we had discussed (#436 (comment)https://github.com/cocos2d/cocos2d-iphone/issues/436#issuecomment-31675943).
> So that's not even a quick fix that we can use.
> 
> As for the code example, I've been doing the latter example like this in
> my examples which I feel reads fairly intuitively. "Center the shape on the
> anchor point" sort of thing.
> CGFloat radius = projectile.contentSize.width/2;
> projectile.physicsBody = [CCPhysicsBody bodyWithCircleOfRadius:radius
> andCenter:projectile.anchorPointInPoints];
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/471#issuecomment-31676057
> .

## 

Martin

**Comment by slembcke** [comment]
Right. This would definitely be something that would add a major delay as it would require a lot of CCPhysics reworking as well as SpriteBuilder changes.

Given how everything else in Cocos works relative to the lower left corner of a CCNode's content rect and not it's anchor point, I feel like it's the correct choice for CCPhysics be consistent regardless of my opinion of how anchor points actually work.

**Comment by slembcke** [comment]
I do like the anchor point corner type idea. I think that is exactly what is wanted here.

**Comment by andykorth** [comment]
I had a lot of trouble with anchor points and children when I was making a few tests. I found it very awkward to get children positioned evenly around their parent- and this was before any scaling or transformations were in play. I eventually got things centered..

But after months of using Unity3D, where this problem doesn't exist at all, it's annoying to work with. Anchor points and the origin of a transform are always the same thing. I've done _a lot_ of Unity, and I complain a lot, but I've never complained about this particular issue, so that's saying something ;)

I can't comment on the amount of work needed to fix this in spritebuilder or with the physics, but it some sort of more convenient handling would be very important to me. Maybe some sort of "reference corner type" would help, but I'd have to see it before deciding. (I'm not 100% sure what it would do).

I meant to make more child position tests, but my time has been taken up elsewhere lately.

**Comment by Birkemose** [comment]
I really have been struggling with this, and sorry if I came across as this being a showstopper. It will not be.

I am not putting any blame on anyone, for me not being able to wrap my head around this. The fact that even Scott is not 100% certain how it works, just illustrates that it is not trivial. It definitely is much different from how chipmunk+v2 worked, but that does not mean it doesn't work in v3.

It is important to me, to make a good template, that will help people understand how to use physics. I will give it an extra bash tomorrow.

**Comment by Birkemose** [comment]
Okay, I finally found a solution, that works reasonably well, with only a few side effects.

Anything more complex than a sphere, where you will never want to resize the sprite alone, should be based on a CCNode. You then use the physicsBody of the CCNode in stead of the physicsBody of the sprite.
This way, you can place, adjust, and do anything you like, without having to worry about anchor points. It works like the physics, in absolute coordinates.

Downside so far, is, that it takes an extra layer of transformations, and that the compound object will have no content size, as it is based on a CCNode.

I am happy with this solution for now.
