### ISSUE TITLE
CCDrawingPrimitives Retirement

### ISSUE THREAD

**Issue by cocojoe** [cocos2d/cocos2d-objc#482]
This okay to retire? It says not to use it anyway and I've removed all references to it and no issues. I'll leave the actual file available for now just in case?

**Comment by Birkemose** [comment]
I vote for removing them. I think CCDrawNode is the standard now for primitives, and as far as I know, its much much faster.

**Comment by slembcke** [comment]
It's mostly faster since it batches, though there is room for improvement in the fragment shader. It's come up a couple of times on the forums lately that CCDrawNode doesn't have enough features to do what people need. So that's somewhere we can add in some enhancements I suppose.

**Comment by Ben-G** [comment]
Yep, I think CCDrawingPrimitives should only be removed once CCDrawNode has some convenience methods to draw different kinds of shapes.

**Comment by slembcke** [comment]
Drawing primitives ended up being removed in 3.1 since the renderer was rewritten. It's possible to reimplement them pretty trivially using [CCRenderer enqueueLines:...], but it would only be good for debugging purposes.

I added https://github.com/cocos2d/cocos2d-iphone/issues/490 with suggested CCDrawNode enhancements to the 3.2 milestone.
