### ISSUE TITLE
Commented out headers

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#483]
I was wondering why ex. CCParticleBatchNode is commented out in cocos2d.h?
Also, some of the functionality in CCTextureCache, is still useful I think.

//#import "CCActionManager.h"
//#import "CCAnimation.h"
//#import "CCAnimationCache.h"
//#import "CCLabelAtlas.h"
//#import "CCParticleSystemBase.h"
//#import "CCParticleBatchNode.h"
//#import "CCTextureCache.h"
//#import "CCTextureAtlas.h"
//#import "CCScheduler.h"
//#import "ccFPSImages.h"

**Comment by cocojoe** [comment]
I would argue that the simple sound header should also be included by default.

**Comment by billhollings** [comment]
Is there any chance that we could move COCOS2D_VERSION (and I guess cocos2dVersion()) out of cocos2d.h and into its own ccVersion.h file?

The reason is that I use declarations based on COCOS2D_VERSION _everywhere_ in **cocos3d**, as a basis for conditional code that is dependent on the version of cocos2d that the user is compiling against.

This will also be true for anyone else building 3rd-party toolsets and libraries based on cocos2d.

It's painful, and sometimes dangerous, to import the _entire_ cocos2d library into every cocos3d file that simply needs to know the cocos2d version. A dedicated version header file would be much more appropriate and helpful.

**Comment by slembcke** [comment]
I thought those were the classes that we decided would become private (perhaps only temporarily) in 3.0. Classes that we were certain would have further API changes in 3.0+ (like CCTextureCache, or the actions) Speaking of which, there was talk of making most of that class methods of CCTexture. (Like how [UIImage imageNamed:] returns a cached UIImage)

Some of those headers like ccFPSImages.h are just plain useless to a developer and only pollute the namespace.

@billhollings
Makes sense to me.

**Comment by Birkemose** [comment]
Yeah. I think ex. the base particles should be included, as they hold a lot of the basic particle functionality. As Martin mentioned, shouldn't sound also be included?
