### ISSUE TITLE
CCAppDelegate incorrectly references screen scales by assumption of device idiom

### ISSUE THREAD

**Issue by phausler** [cocos2d/cocos2d-objc#517]
In CCAppDelegate.m the UIScaleFactor (and associated calculations there-in) incorrectly assume that the window's screen's scale is either 1.0 or 2.0. This is definitively not the case in Apportable based screen modes that can potentially return reasonable values ranging from 1.0 to 4.0 depending on the device's hardware size (conceivably it could return any positive float value depending on configuration).

The magic numbers of 1.0 vs 0.5 vs 2.0 should all be calculated from a canonical source of the current CCGLView's screen's scale value.

As a side note this also has a side effect of also preventing proper UI resolution settings on AirPlay displays since technically they can return values that are not 1.0/2.0

**Comment by slembcke** [comment]
Cocos2D's assumptions about valid content scales have been (almost) completely removed in 3.0. (Though CCConfiguration is still very problematic) The content scale is initially copied from the UIView used with Cocos, but can be changed to any value including fractional ones. UIScaleFactor is used as a multiplier for keeping the physical size and layout of UI elements consistent across device types, and is not the same as the content scale.

The 2x tablet scale option is so you can treat a tablet as though it's phone that's roughly twice as big physically. With this enabled, it doubles whatever the native content scale is. For example it will set up a retina iPad to have a coordinate system of 512x384 points and a pixel to point ratio of 4:1. The UIScaleFactor value is set to 1/2 so that UI elements will be roughly the same physical size as on a phone. The 2x scale option is not default, and is a convenience only. The developer can set up their content scale factor and UI scale factor however they wish, including fractional values if muddy texture filtering can be tolerated. The magic numbers you are referring to are only a rough estimate of the physical size differences between phones and tablets and are not as fragile as assumptions about the resolution or native content size. They are certainly never compared for equality like was done in earlier versions of Cocos.
