### ISSUE TITLE
Cocos2d projects should default to building arm64 architecture

### ISSUE THREAD

**Issue by LearnCocos2D** [cocos2d/cocos2d-objc#534]
Cocos2d project Architecture setting is set to armv7 and armv7s, excluding arm64. 
When linking with another library that includes arm64 or (as in the SpriteBuilder generated project) when the cocos2d.xcodeproj is referenced in the project and only the app's target is changed to include arm64 architecture, linker errors occur (file was built for archive which is not the architecture being linked).

Including arm64 architecture requires bumping the default deployment target to iOS 5.1.1.

It's straightforward for devs who (still?!) want to support iOS 5.0 or earlier to remove arm64 from the architectures list - they get told by Xcode if they don't. 

It's less simple to add arm64 support because it may suddenly cause new compile errors in one's own or cocos2d code. Case in point, even in cocos2d 3.0 alpha there are "multiple methods named xxx found" errors in CCActionInterval and CCBAnimationManager that only crop up when you build for 64bit device/simulator with arm64 in the architectures list.

Btw, current official usage stats see only 3% usage of iOS 5 and earlier. 
Back in September 2013 iOS 5 usage was 5% with earlier iOS only 1%. 
Sources:
https://developer.apple.com/support/appstore/
http://stackoverflow.com/questions/15967143/where-can-i-find-ios-versions-statistics

**Comment by richardgroves** [comment]
Is the library ready for 64bit yet? With CGFloat becoming double rather than float wont a whole bunch of code need extensive looking at, if not reworking, to avoid precision issues.

For example:

CGFloat
ccpLength(const CGPoint v)
{
    return sqrtf(ccpLengthSQ(v));
}

will pass a double into sqrtf, which converts it to a float and returns a float, that is then converted to a double in the function return type - precision is lost.

This is probably all happening on the 64bit Mac OSX target anyway already so is probably not an issue, but...

**Comment by slembcke** [comment]
This should all be taken care of in the latest git code.

**Comment by slembcke** [comment]
This should all be taken care of in the latest git code.
