### ISSUE TITLE
CCTextureCache doesn't remove unused textures in time...

### ISSUE THREAD

**Issue by iMobCoding** [cocos2d/cocos2d-objc#554]
I know you plan to re-factor **CCTextureCache**, but right now I see a problem where texture cache keeps unused textures all the time. In cocos2d v2 I used to call

```
[[CCTextureCache sharedTextureCache] removeUnusedTextures];
```

in **dealloc** method of the outgoing scene. I tried that in latest v3 and when I call **dumpCachedTextureInfo** in the new scene, it still shows that textures from the previous scene are there. I checked if previous scene is dealloc-ed before I called dump info, and it is. Interesting thing is, if I call **[self removeAllChildren]** manually, before removing unused textures, then it works as expected. I doubt we should manually remove children on an outgoing scene?

Best

**Comment by slembcke** [comment]
We have a couple rough tests that show that it's working, though it's hard to fully unit test it.

Are you certain that the textures aren't being retained in a cycle somewhere? Perhaps the scene was deallocated, but some of the child nodes were not? Have you tried running the leaks instrument?

**Comment by iMobCoding** [comment]
Yes I am sure there are no leaks in my code. But leaks will not show what's captured in TxtCache singleton. So, here is a link to simple test:

https://dl.dropboxusercontent.com/u/5351290/ForSharing/TxtCacheTest.zip

Created from cocos v3 template, so nothing fancy there. Two scenes with two images. Start demo, tap on "Dump Cache Info" on 1st scene to see only one image there. Go to next scene, tap "Dump Cache Info" and you'll see old image is still in cache. Return to original scene and see both images still in cache...

But please check **dealloc** method in both scenes, where I commented "removing all children". Now un-comment those in both scenes and you'll see that textures are removed from cache...

Best

**Comment by slembcke** [comment]
Hmm. That's pretty weird. I'll look into it.

**Comment by slembcke** [comment]
Sorry this took so long to get back too. It seemed odd when I first looked at the source a couple weeks ago, but I figured out what was going on here. It's actually working correctly, you just need to move some of your operations around. You should have run into the same issue in v2 actually.

So here is what is happening. You are creating the next scene and passing it to the transition. While the transition is running, both scenes are in memory at the same time. When the transition finishes, the first scene gets dealloced. Flushing the texture cache from the dealloc method doesn't really do anything since the scene is dealloced before it's child which is holding the texture reference open. This happens going both ways, so unless the texture cache is flushed some other time, it will never actually decrease.

It is still working correctly because if you explicitly trigger a memory warning, it will flush the cache when only a single scene is in memory.

If you want to fix your example, you need to move the cache flush call to your scenes' onEnter methods and avoid using transitions. Since it's not actually leaking memory I wouldn't really worry about it though unless you are switching between two scenes with very heavy memory usage. In that case, you simply cannot use transitions if you can't afford to have all of their assets in memory at the same time.

I also put in a fix so that the previous scene will be released before calling the second scene's onEnterTransitionDidFinish method. That way you could flush the cache there if you wanted to.

**Comment by iMobCoding** [comment]
I understand what you're talking now, and it's actually working if I flush the cache in **onEnterTransitionDidFinish** but trust me that wasn't the case in v2. For example, I have a game scene and on top of it I call Pause Layer with some graphics. When I close Pause layer I used to flush cached textures in its dealloc method, so Pause layer's memory is freed when I am back to my game. What you're suggesting now isn't doable. If I flush textures in Pause's dealloc method it will not be freed... Can you please check how it was done in v2 because that's how I worked for a long time in the past - flushing everything in dealloc of the outgoing scene, no matter if I used transitions or not...

Best

**Comment by iMobCoding** [comment]
Edit: As Pause layer goes in and out without any actual transition, I thought if I place remove unused textures in dealloc method everything should work - but it doesn't. Only if I place [self removeAllChildren] before removing unused textures (in dealloc method) everything still works. So I think problems lies in something else and it's not related to CCTransition keeping the children. Somewhere code to clean up the outgoing nodes isn't fired in time... Simply, removing / cleaning up all the children should happen before the actual dealloc method is called. I think that's how it was in v2...

**Comment by slembcke** [comment]
The difference is that V2 didn't use ARC and you presumably flushed the texture cache after calling [super dealloc] which would have freed all the node's children. ARC implicitly calls [super dealloc] last. You simply cannot do this anymore unless you want to disable ARC.

Another option that is a little cleaner is to release all the children and flush the cache in the onExit method. In general though I wouldn't worry about the texture cache. It gets flushed automatically by low memory warnings. If you explicitly flush it all the time it's not really doing it's job.
