### ISSUE TITLE
Adding a joint from within a callback may trigger assertions.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#567]
CC2D Forum thread:
http://www.cocos2d-iphone.org/forums/topic/changing-from-dynamic-to-static-cocos2d-v3/

"I then tried to make a joint at the point of collision but it doesn’t work right."
Haven't had a chance to reproduce the issue yet, but I assume that would trigger assertions as well.

**Comment by Chiglit** [comment]
Hey, I actually posted that. 

Regarding the joint, I was referring to how it moved. Wasn't what I was hoping for, it didn't error, just wasn't what I was expecting to happen.

Would be interesting to see if this is really a bug and can be fixed for the next release since the "feel" of my game depends on it. :D

**Comment by slembcke** [comment]
I double checked and it is handled properly. Apparently I was (almost) totally on top of that a few months ago.
