### ISSUE TITLE
Setting position manually on static CCPhysicsBody

### ISSUE THREAD

**Issue by Ben-G** [cocos2d/cocos2d-objc#570]
I ran into this a couple of times now.

To me, intuitively, it should be possible to manually set a position for a static body and move it around in the scene. I only consider it static for the physics calculation. You run into this problem when you try to scroll static CCPhysicsBodies.

**Comment by slembcke** [comment]
Not sure I understand your meaning exactly? You can change the position of static bodies, but it's not going to produce very smooth motion and it can get pretty expensive since you are making a body that is optimized to not move, move. Plans are in motion to be adding proper kinematic bodies that support actions and such if that is what you are after.

"You run into this problem when you try to scroll static CCPhysicsBodies." Like moving a whole screen full of static bodies? That's _definitely_ something you don't want to be doing. The static bodies should not be moving (relative to the physics node anyway). The scene or some parent node should be moving instead.

**Comment by Ben-G** [comment]
Sorry, I realized I wasn't very clear on this. I'll try to give a more detailed explanation. 
Assume the situation of a MainScene.ccb and a Level.ccb in SpriteBuilder.

The Level.ccb contains obstacles, all static physics bodies:
![screen shot 2014-02-07 at 10 07 45](https://f.cloud.github.com/assets/1423068/2112766/3de50db4-9023-11e3-9e12-d82177316742.png)

The MainScene.ccb includes this level as a Sub-CCB-File:
![screen shot 2014-02-07 at 10 09 00](https://f.cloud.github.com/assets/1423068/2112774/5f5e6760-9023-11e3-9c62-c443cf7934b3.png)

Last, I set up a code connection to access the Sub-CCB-File Node in Code. This is where I modify the position of the Sub-CCB-File. I move the whole Level.ccb to the left.

This is what happens:
Any physics objects in the Sub-CCB-File will not be moved, however any other CCNode that is not a physics object will move (e.g. a Label).

I'm sure there are a lot of good reasons to treat the _parent transform_ of physics objects differently, however I wonder if there is a (different) way to move a CCNode that contains many physics objects and make the physics objects move with that parent.

**Comment by slembcke** [comment]
Ooh. I see. This is something I spent a lot of time thinking about a few months ago actually. I could go on about it for quite some time about all the problems and tradeoffs, but the solution taken in the end was the simplest and most efficient. Treat active physics body transforms as relative to the physics node and not the transforms of the parent nodes.

The alternative that I would definitely recommend is to have the player move to the right and move the entire physics node over to keep the player at the edge of the screen. Since the actual physics simulation is done relative to the physics node, the physics doesn't need to do or update anything. This is _vastly_ more efficient and would scale just fine to a level with many more objects.

Doing scrolling games in Cocos2D is sort of weird since it has no concept of a camera. The screen is fixed, and you move the content around to scroll. This mindset has gotten people in trouble when they try to make physics based games like this where they think of the player as being stationary and the level being the part that moves. Since that's not how the actual physics works you can end up making some fairly broken assumptions.

**Comment by Ben-G** [comment]
> The alternative that I would definitely recommend is to have the player move to the right and move the entire physics node over to keep the player at the edge of the screen.

Yes, I have used this approach in my previous side scroller. 
Since so many people want to make the level scroll intuitively I wanted so see if there is a way to make that work.

Also if you want to implement a procedurally generated level some thoughts seem a little more straight forward (spawn new obstacles at the right edge of the screen, remove obstacles when they leave the left edge of the screen). 

I'll go with your suggestions. Thanks a lot!
