### ISSUE TITLE
Framerate information flickers when use CCRenderTexture

### ISSUE THREAD

**Issue by DSalko** [cocos2d/cocos2d-objc#574]
If scene has CCRenderTexture, framerate indicator flickers between zeros and normal values.

**Comment by Taum** [comment]
This is because `[CCRenderTexture begin]` calls `[CCDirector setProjection:]` which re-creates the labels and sets their text to "0". Since the label texts are only set every `CC_DIRECTOR_STATS_INTERVAL`, they appear as "0" until then.

The problem can be fixed by either commenting the `if (_accumDt > CC_DIRECTOR_STATS_INTERVAL)` or moving the call to `createStatsLabel` from `[CCDirectoriOS setProjection:]` to somewhere else (`reshapeProjection:` worked for me). I don't know if there is a better solution but maybe a maintainer can comment on this?

Hope this helps !

**Comment by DSalko** [comment]
Thanks, Taum. Your fix works well.
