### ISSUE TITLE
develop v3 : OALSimpleAudio play effect delay on Android

### ISSUE THREAD

**Issue by jjxtra** [cocos2d/cocos2d-objc#575]
On Android via Apportable, sounds are delayed by about 1/2 second. This happens even with preloading. Sound effects are caf files, and I've attached one here as an example.

Device is a 2013 Nexus 7, Android 4.3.

**Comment by slembcke** [comment]
Sound seems to be really picky on Android with different devices and system software versions causing buffering issues. Do you have any other devices you can test with to see if it's hardware specific.

The sound on [this project](https://github.com/slembcke/CCPhysicsColorMatch) works fine on our 1st gen Nexus 7 running 4.2. Might be worth trying to see if that runs correctly?

**Comment by jjxtra** [comment]
I will try this project and let you know. Is this run with the latest github code or RC1?

**Comment by jjxtra** [comment]
One thing I noticed is that your project has wav files. Mine is using caf files. I'll convert my caf to wav and see if that fixes it.

**Comment by slembcke** [comment]
The Cocos library code in that was slightly pre-RC1, but we haven't touched the ObjectAL code for a while. So I don't think that should matter.

**Comment by jjxtra** [comment]
Tried the pop.wav file in my project and there was no delay. My .caf files had delays when I swapped them out with the sounds in that sample project you sent, so I think we can say the problem is limited to .caf files, and that Apportable will be the ones needing to fix it.

**Comment by slembcke** [comment]
Hmm. I was sort of wondering if it was because it was trying to use hardware decoding to play the files and causing a delay to start playing them. I tried tracing through the ObjectAL code the other day, but couldn't find a code path for sound effects where it didn't load the file into a regular AL buffer.

I figured it was a dead end idea, but his makes me suspicious again... Did you let the Apportable people know about it? Sounds like it's something the Apportable people will need to fix, or will need to be a patch to the ObjectAL source.

**Comment by jjxtra** [comment]
I have let the Apportable team know, here is the issue: =660&colspec=ID%20Type%20Status%20Milestone%20Owner%20Summary%20BlockedOn%20Component%20FoundIn%20FixedIn.

Also included in this issue is a problem with really bad stuttering sprite movement on Android.
