### ISSUE TITLE
v3 : CCParticleSystem assert firing

### ISSUE THREAD

**Issue by jjxtra** [cocos2d/cocos2d-objc#601]
When setting autoRemoveOnFinish to a particle system in a particle batch node, sometimes this assert fires (index and _totoalQuads are 0, amount is 100). Pretty reproducible in a small app I'm making, happens within about 5-10 seconds of spawning a particle system every second.

-(void) removeQuadsAtIndex:(NSUInteger) index amount:(NSUInteger) amount
{
    NSAssert(index + amount <= _totalQuads, @"removeQuadAtIndex: index + amount out of bounds");
...
}

**Comment by araker** [comment]
This bug has been in the code since v1.1. I came across it a few weeks ago,  it's because the particle is system is deleted too soon in the sequence. Looking at the code in v3.. https://github.com/cocos2d/cocos2d-iphone/blob/develop-v3/cocos2d/CCParticleBatchNode.m

So in -(void)removeChild: (CCParticleSystemBase*) child cleanup:(BOOL)doCleanup

the call to [super removeChild:child cleanup:doCleanup]; should be below [child setBatchNode:nil];

Else the child could be removed before removeQuadsAtIndex executes, hence the assert firing.
