### ISSUE TITLE
__unsafe_unretained should be __weak for member ivars and properties (i.e. delegates).

### ISSUE THREAD

**Issue by jjxtra** [cocos2d/cocos2d-objc#611]
As far as I know iOS 4.X is not being supported, so all __unsafe_unretained should become __weak... CCGLView is one culprit.

**Comment by slembcke** [comment]
I've been suspicious of a few of the uses of __unsafe_unretained also. There are a couple I've fixed that were definitely wrong, but I left the ones I was unsure about. They probably should be moved to __weak variables though.

There are places like in CCScheduler where __unsafe_unretained variables are used (carefully) on purpose. ARC was otherwise using up _huge_ amount of the CPU time on unnecessary, synchronous retain counting operations. Having similar issues with the new rendering code for 3.1 actually.

**Comment by davilca** [comment]
People, __unsafe_unretained is useful to avoid unnecessary retain/release instructions. I use it a lot inside loops, in this form (recommended by Apple if I remember well):

CCSprite \* __unsafe_unretained spr;
for (spr in someArray) { }

It has advantages if used carefully and on purpose, as @slembcke said.

**Comment by jjxtra** [comment]
For tight loops that's great, but for member ivars and properties, probably not a good idea, which I see in the cocos2d-iphone code. __weak should be used for any member ivars or properties that should not be retained.

**Comment by slembcke** [comment]
Finally gave the source another pass. Found at least one usage of __unsafe_unretained that may have been a bug. Changed a few non-performance critical ivars to __weak.

**Comment by jjxtra** [comment]
Thanks for looking through those, hopefully all retain cycles are squashed :)
