### ISSUE TITLE
make `button` readwrite as the content for the CCTableViewCell

### ISSUE THREAD

**Issue by tchaikov** [cocos2d/cocos2d-objc#613]
I'd like to have more control over the appearance of the table cell, but the `button` in `CCTableViewCell` is a readonly property. one can hardly replace it with a customized `CCButton` or a `CCNode` instance.

one way to achieve this goal, we can expose `button` as a readwrite property of type `CCControl`. in the setter of it, we remove the current `button` from `CCTableViewCell` 's children, and connect the `[CCTableViewCell pressedCell:]` with the control's `block`, so the desired action can be triggered as it is now.

**Comment by kalo** [comment]
`CCTableViewCell` is intended to be plainly generic, practicing UITableViewCell from UIKit. while considering the `button` can still be customized much as any CCButton could and nodes may also be arbitrarily added, although not propagated through a property. 

deviation from the standard design is necessary in most cases, and perhaps the better way of doing so would be to subclass the view cell rather than making the core class malleable. this way features can be added or changed as pleased.

**Comment by tchaikov** [comment]
john, thanks for your reply !

>  `button` can still be customized much as any CCButton could and nodes may also be arbitrarily added, although not propagated through a property.

yes, maybe i can take `CCButton` as the `contentView` in `UITableViewCell`. and do the layout when creating it. will give it a try before creating a subclass of the table view cell.

> deviation from the standard design is necessary in most cases, and perhaps the better way of doing so would be to subclass the view cell rather than making the core class malleable. this way features can be added or changed as pleased.

yes, this solution is more flexible.
