### ISSUE TITLE
Sprite Batch Node and Vertex-Z don't render correctly

### ISSUE THREAD

**Issue by davilca** [cocos2d/cocos2d-objc#624]
As I have commented days ago, Vertex-Z and Sprite Batch Nodes don't render correctly, so don't work correctly.

These are the known bugs (after doing some tests):
- Transparency isn't rendered correctly. Transparent pixels are drawn opaque, with the color of the background, so you cannot see other sprites behind that transparency.
- Negative Vertex-Z values don't work. The sprites disappear from the screen. Negative values worked as expected in v2.1. For example, if spr1.vertexZ = -2 and spr2.vertexZ = -1, spr2 was rendered on top of spr1.

Explaining of the transparency bug (using the vertexZ test uploaded by Birkemose):

![vertexz-bug](https://f.cloud.github.com/assets/371049/2294185/9d4c17c4-a07d-11e3-9cae-de970bace4ad.png)

I really recommend you to use simple and irregular forms to test this issue.

**Comment by slembcke** [comment]
Reposting from the forums:
The transparency issue in the test was due to using the default shader. That is fixed easily enough. Not really a bug per-se considering that you’ve always had to explicitly enable alpha testing.

The negative z value thing is weird… The negative z-values in the VAO are ending up as 4.294970e9. Suspiciously close to 2^32. I couldn’t find anywhere that casting to an unsigned integer accidentally. Near as I can tell, the relevant code hasn’t changed since 2.x either.

**Comment by slembcke** [comment]
Randomly occurred to me while eating lunch is that the only place that unsigned integers could be involved is due to C's implicit type coercion rules (ugh...) and the arc4random() function. The negative values work just fine if you add a cast to float before negating the value.
`node.vertexZ = -(float)(arc4random() % 100);`

Both issues here were just issues in the test and not bugs in Cocos2D unless there is something else.

**Comment by davilca** [comment]
Ok, I was enabling alpha testing in the wrong way, sorry for that... This is the correct way:

_cardNode.shaderProgram = [[CCShaderCache sharedShaderCache] programForKey:kCCShader_PositionTextureColorAlphaTest];

@Birkemose should update the test with that line, it can be a bit confusing. Negative values work as expected too.

Thank you very very much for your help and time, @slembcke. Closing this!

**Comment by Birkemose** [comment]
Default shader and blending should work "as expected" witout doing anything, so I should not add any extra line of code for that. If an extra line of code is needed, default behaviour is not correct.

The test was only for vertexZ, but I agree, that for correct blending testing, the playing cards are not ideal.

**Comment by davilca** [comment]
Then the default behavior you intend is not correct at the moment, I suppose, because you need to mandatory set the "alpha test" shader to the batch node. The default behavior in v2.1 was just like it's now: you needed to set the new shader program. So, to me, this is solved.

Maybe the ideal case would be to config depth buffer only, and then the rest would work out of the box.
