### ISSUE TITLE
CCControlSubclass.h is unneccessary

### ISSUE THREAD

**Issue by nheagy** [cocos2d/cocos2d-objc#628]
It seems to me that the point of CCControlSubclass.h is to limit some methods from being exposed publicly. If that is the case, that's not really important—this is Objective-C, after all. 

Let's get over the desire to have protected methods in a language that doesn't even really do private, and put these methods in CCControl.h

**Comment by slembcke** [comment]
Methods that are merely implementation details should _not_ be exposed as part of the public API. C and Objective-C may not have explicit visibility qualifiers, but it's entirely common to control visibility through what is exposed in the headers. Some methods might be dangerous to call and can leave objects in an invalid state unless you really understand what they do. Some methods are just plain unhelpful to a user of the class and you wouldn't want them in your autocomplete lists (like the subclass header). Some might be useful, but only because the current implementation use a particular data structure. Etc.

Unlike Apple's private APIs, you are entirely free to use the private headers with the understanding that there is no intention to make them compatible between minor versions. Data structures may change, methods may be removed or have their behavior changed, etc.

**Comment by nheagy** [comment]
Here's one more attempt to persuade you. First, after re-reading my comment it probably came off as more smarmy than intended. I ought to have put more care into it.

To be specific, I think these methods ought to be public on iOS:
- (void) triggerAction;
- (void) touchEntered:(UITouch_) touch withEvent:(UIEvent_)event;
- (void) touchExited:(UITouch_) touch withEvent:(UIEvent_) event;
- (void) touchUpInside:(UITouch_) touch withEvent:(UIEvent_) event;
- (void) touchUpOutside:(UITouch_) touch withEvent:(UIEvent_) event;

and for mac, the mouse\* equivalents.

While some of the other methods in CCControlSubclass could needlessly alter state like you mentioned, these should pose no such threat. They are basically clever equivalents to UIKit's UIControl events.

Making them public would have two advantages:
1. Subclassing CCControl is far more straight-forward for the majority of cases, as most subclasses probably just want these events and not the stateChanged…needsLayout methods that could affect internal state.
2. Testing becomes easier. I've personally only encountered one UIKit API that has a header for subclassing: UIGestureRecognizer. It's also one of the hardest parts of UIKit to involve in automated testing…

Either way, thanks for your initial reply with explanation.

**Comment by vlidholt** [comment]
As the documentation clearly states for CCControl:

_Important: If you are sub-classing CCControl you will need to include the CCControlSubclass.h file as it includes methods that are otherwise not exposed._

Including the CCControlSubclass.h will expose the methods you need for doing a subclass. These are methods that should not otherwise be used or called directly. Including them in a special header file that you include from your subclass is a common design pattern and is used in Apple's newer APIs.
