### ISSUE TITLE
Simplified particles

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#646]
A trick I have been using to improve particle systems, is using a triangle, in stead of a quad. For a lot of "organic" particles, like fire, rain, etc, you not only can reduce the number of transparent pixels dramatically, but you of course also can divide geometry by two.

**Comment by MKGitHub** [comment]
Assuming there is no texture on the particles, just a color, right?
Or is there a texture, and if so, how would you then map it on a triangle?

**Comment by Birkemose** [comment]
No, it is textured. The texture will of course be square, but then you just map the triangle into that. Imagine a rain drop. 
![drop](https://f.cloud.github.com/assets/844912/2395872/02779122-a9d0-11e3-837e-b3510b9190d0.png)

**Comment by MKGitHub** [comment]
Would be interesting to see performance and possibilities of this technique vs quads.

Is there a tool that can tell the number of transparent pixels in an image? Could be interesting to use that for comparison, besides lowering the vertice count.

**Comment by slembcke** [comment]
This came up a little bit in one of the other enhancement threads too.

There was an old article I remember that talked about the performance implications of fitting convex hulls around particles. I can't find it, but the basic idea was that trimming particles this way works well and can reduce your fillrate by quite a bit. Performance is better as long as triangle count is kept very low (I vaguely recall like 3-4 triangles per particle, but I don't really remember hardware details or anything).

I was able to find the old tool I was thinking of though:
http://www.humus.name/index.php?ID=266

It wouldn't be hard to make something similar.

I'm going to implement particles as is for 3.1, but we should definitely add something like this soon.

**Comment by Birkemose** [comment]
I think you would have to count the transparent portions manually (and correct for transparent pixels being faster to render if the entire tile is transparent), but the performance boost is quite significant on some particle systems. I used it for fire systems a while back, which probably is one of the most heavily overdrawn particle systems you can make.

I am a strong believer in trading fill rate for bandwidth, especially in portable GPU's, and with SpriteBuilder we actually have a tool that at some point could assist is doing this.

**Comment by MKGitHub** [comment]
Would have to use single image/texture for this to work and not an atlas right? ...assuming that some polygon vertices may "go out of bounds" like in this image. Or perhaps place all the images mapped with their polygons in such an optimized way that it would work in an atlas.

![particlepolys](https://f.cloud.github.com/assets/535550/2430724/27b3d3a4-ad01-11e3-911d-dc4fb65be75d.jpg)

**Comment by slembcke** [comment]
That's something that could be experimented with. Cocos particle systems currently don't work with texture atlases at all (something I'd like to change actually).

Not sure how they implemented the hull reduction algorithm in the picture above since the quadrilateral and triangle cases only share one splitting plane. I think in the general case the optimal way to do it is probably to first build a detailed hull that contains all vertexes. You can think of each edge of the hull as a corner that was cut off. Iterate all the edges and find the corner that contributed least to the overall area and add it back. Iterate until you have reduced the vertex count sufficiently. To prevent it from exceeding the texture's original bounds, you could ignore edges that would add an out of bounds vertex if removed.

**Comment by slembcke** [comment]
Pinging this for #1163
