### ISSUE TITLE
Changing gravity has no effect on stationary objects.

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#648]
If a object is stationary in zero gravity, setting gravity will not affect the object, until a force is applied to it. After that, gravity will work as expected.

**Comment by slembcke** [comment]
I bet it's because the object is sleeping, since that is enabled by default in CCPhysics. Properties that affect bodies/shapes wake bodies up when they are changed. The space level properties should potentially wake everything up. I'll have to put think about this for Chipmunk.

A workaround for now would be to disable sleeping on the ChipmunkSpace using CCPhysicsNode.space.sleepTimeThreshold = INFINITY.

**Comment by slembcke** [comment]
Since this is a Chipmunk bug, I'm moving the issue there:
https://github.com/slembcke/Chipmunk2D/issues/92
