### ISSUE TITLE
Global z-order.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#662]
I brought this up a few months ago for 3.0, but I was proposing replacing the current sibling relative z-ordering with global z-ordering instead of extending it. The idea was brought up again [in a forum thread](http://www.cocos2d-iphone.org/forums/topic/v3-1-rendering-progress/), so I figured I'd make a discussion thread for it on GitHub.

At the renderer level, this would just be a sorting value that gets added to each drawing command. The easiest way I can think of to make this backwards compatible is to give everything a default global sort value (0 as a float?) and then use a stable sort. The only modestly tricky part would be render textures and clipping nodes. They would need their own queue so that it could be sorted independently from the rest of the scene.

The biggest reason I've avoided the idea more recently would be how to expose the API for it? I feel bad about adding even more functionality to CCNode, but what do people think of CCNode.renderSequence? It avoids having another property with "z" in the name to get confused by. Unity calls the same property renderQueue in their APIs, but I feel like that is a bad name.

@Birkemose Any ideas on how you would implement the methods you suggested in the forum thread?

Lastly, it seems like the global sorting order should be applied to the CCResponder code as well. Agreed? The only thing we would need to change would be to apply a stable sort after rebuilding the responder list.

**Comment by Birkemose** [comment]
About global z, here is what I worked with some time back.

I would maintain z as it is now, because it works really well. The main thing I have stumbled upon, are where you want to insert a sprite into a batch, or insert a sprite into a compound object.
The former could be inserting a character into a parallax map, and the later could ex. be an object with an attached particle system, where the particle system should follow transformations of its parent, but ex. always should be on top.

I have not digged into the guts of 3.1 yet, but how a normal centralised render engine works, is by recursively iterating the nodes as normally (as in 2.x), but in stead of rendering them immediately, it adds them to a big buffer, with an attached render state. After that is done, the big buffer is scanned, and each time the render state changes, a new batch is created. 

While it certainly is possible to maintain a global z, I think it in most cases would be very cumbersome to the user. In stead, what I was thinking of back then, was to add functionality like
[myNode placeInFrontOf:anotherNode];
[myNode placeBehindOf:anotherNode];
[myNode placeDefault];

The only thing this requires, is that in stead of adding the node data and renderstate to the end of the big buffer, it should be possible to add it anywhere. How to do this, would depend on the big buffer. The good thing would be, that all this could be handled in the central renderer, and would add very little code and complexity to the nodes.
In my own implementation I used a fixed size big buffer, so inserting a node would be rather expensive. In that case I see two scenarios.
1) 
Node A must be rendered behind or in front of node B, but node B has not been rendered yet.
In that case, node A should be rendered to a temporary buffer, which can be used when node B renderes
2)
Node A must be rendered behind or in front of node B, node B is rendering, but node A has not been rendered yet.
In that case, node B should allocate place in the big buffer, for when node A is rendered.

Hope this makes sense.

**Comment by vlidholt** [comment]
I'm not a super big fan of this idea as I think it will add more confusion/complexity (and possibly performance issues) than problems it will solve. As @slembcke mentioned, what do we do with render nodes, effects nodes, clipping etc? If we are adding it, we need to find some real world use cases first – cases that cannot easily be implemented with the current solution. The issues that @Birkemose are mentioning are mostly already handled by the new renderer (e.g. inserting a sprite in a batch node).

Generally, I think that there are cleaner ways to solve these problems than by adding a global z. But, I can be convinced otherwise if there are strong cases and it doesn't affect performance too much. I'm thinking of the sorting time here – it's probably much less expensive to sort smaller arrays (the individual node's children) than all nodes at once every frame.

The behavior of:
`[myNode placeInFrontOf:anotherNode];
[myNode placeBehindOf:anotherNode];
[myNode placeDefault];`
is not entirely clear to me. E.g. what happens if you remove a referenced node? Seems tricky to write this code and maintain all connections correctly?

In what form are cocos2d-x adding this? It seems to be something we could add in a later update without changing the API too?

**Comment by slembcke** [comment]
I've probably implemented hacks around the lack of a global z-order on more than half the Cocos games I've worked on. Mostly due to the same reasons as @Birkemose. I want an effect (shadows, glows, particles, etc) that follows a particular sprite, but always want it to be on top or below all similar sprites. These are pretty common effects. Had it been available, I would have used it in the Caustic Caverns demo to separate the water from the hierarchy's draw order when trying to layer the lighting effects and such. I would use it with CCPhysicsNode to move the debug drawing above everything in the scene where it can't be obscured instead of just above the children. To implement this without it being built into the rendering code, I always have to make something that manages several nodes and synchronizes them each frame. If any of the parent nodes have non-trivial transforms it becomes difficult quite quickly.

Exposing something like the CCNode.renderSequence I proposed above would be pretty easy. Making the change to how render textures and clipping nodes handle it would be fairly easy if we added it as a core feature now instead of trying to extend it later. Performance-wise it wouldn't cost anything if you don't use it.

The other possibility is to expose it only in the renderer API and not CCNode. I've been considering adding this either way as a "for me" feature for quite a while. Rendering commands would be assigned a sorting value, so custom rendering can take advantage of the feature. Default rendering functions would simply pass 0.0. This would avoid having too many Z and sorting related properties on CCNode to confuse beginners. More advanced users would still have fairly easy access using custom drawing methods. Then, later we can decide how and if to expose it at a higher level.

Cocos2D-x is doing it like I was suggesting above. An node property that defaults to 0.

**Comment by vlidholt** [comment]
Ok, you made a pretty strong case here. ;)

To me, the renderSequence property makes the most sense, it's easy to understand and should have a more clear implementation than the placeBehindOf/placeInFrontOf concept. If it doesn't affect performance much and can work sensibly with render nodes, effect nodes, etc, I think this would be a good feature to add.

**Comment by slembcke** [comment]
This has been implemented at the CCRenderer level now. I'm moving this issue forward to the next release if we want to do more discussion about how to expose it at the CCNode/sprite/whatever level.

**Comment by Ben-G** [comment]
Any update on this? Once again could make good use of it ;)

**Comment by slembcke** [comment]
This has been implemented internally since 3.2. It will be exposed by CCRenderableNode in 4.0.
