### ISSUE TITLE
CCPhysicsNode with multiple shapes rotates funny

### ISSUE THREAD

**Issue by jjxtra** [cocos2d/cocos2d-objc#684]
When applying angular velocity to a CCPhysicsBody with multiple shapes, the rotation is kind of funny. I would expect the rotation to happen around the center of my sprite, but instead it rotates around the center of the physics bodies. Perhaps an option to toggle the center of rotation would help?

**Comment by slembcke** [comment]
It's a physical law that a rigid body rotates around it's center of gravity when in free fall. Rotating around any other point would require forces to be acting on the body.

The center of gravity is calculated by assuming a constant density within each shape. You can influence where the CoG will end up by changing your shapes' masses. Using the Chipmunk APIs you can set the CoG to an explicit value. You may want to adjust the moment of inertia if you do that though.

If this is something that people want to do more often, we could talk about adding it to the CCPhysics API. A big part of why it calculates all of this for you is because it's really easy to get wrong. There is a lot math involved that most people don't want to worry about.

**Comment by jjxtra** [comment]
Gotcha. Thanks for the clarification. Will close.

**Comment by jjxtra** [comment]
Just FYI this helped me get the throwing knife for Birdshot on iOS just right. The handle has a little less mass than the blade and now that I understand how this works, the knife rotation when it is thrown looks great!
