### ISSUE TITLE
CCTableview doesn't display correctly

### ISSUE THREAD

**Issue by mattcn** [cocos2d/cocos2d-objc#686]
I have an issue on CCTableview from cocos2d v3. I use the cctableview and add it as a child of a background sprite. but the cells from CCTableview is displayed not only inside the background content size, but for the border sometime will show outside the background. See the screenshot attached, the red line area indicates the background view of the cctableview.
![tableview_ex](https://cloud.githubusercontent.com/assets/772040/2642342/8148d0d2-bf07-11e3-8886-c004fe54fafa.png)

**Comment by mattcn** [comment]
I have fixed this by adding a clipping node, however, the outside area is still touchable for the cells? any ideas to fix this?

**Comment by richardgroves** [comment]
I had the same problem of a tableview drawing outside of the region I
wanted - CCTableView and CCScrollview are a bit of a pain if you don't have
them cover the full width of the screen. I adapted some old clipping node
code that uses GL_SCISSOR rather than the CCClippingNode mask -
https://github.com/NoodlFroot/ClippingNode. But I hadn't noticed that I
could click outside the clipped region..

I'm thinking of trying to add a touch filter into the clipping node so that
any touch outside the clip region is not passed down to the children, but
suspect I'll have to get into the details of the responder chain to manage
that.

On Tue, Apr 8, 2014 at 1:37 PM, mattcn notifications@github.com wrote:

> I have fixed this by adding a clipping node, however, the outside area is
> still touchable for the cells? any ideas to fix this?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-iphone/issues/686#issuecomment-39842389
> .

## 

Richard Groves
Technical Director | NoodlFroot

M: +44 (0)7962 054 163

www.noodlfroot.com

NoodlFroot Limited is a company registered in England and Wales with
registration number 07245048.
Registered office: 145-157 St John Street, London, EC1V 4PY.

**Comment by vlidholt** [comment]
Good point, touches outside the scroll area shouldn't be passed down.

**Comment by slembcke** [comment]
Any ideas how to implement that? Right now the responder code works using a front-to-back search and not a hierarchical one. This makes a lot of sense since most nodes aren't content nodes (unlike in UIKit).

If we want to make it be a hybrid system, we could give the table view it's own responder manager that passes claimed touches to it's children. Instead of always adding nodes to the singleton manager, search up the node hierarchy instead. Seems like it might be a fairly straightforward change?

**Comment by fallhunter** [comment]
the same problem

**Comment by slembcke** [comment]
Scrollviews in v4 will finally clip their contents. \o/
