### ISSUE TITLE
Emoji Smiles in CCLabelTTF

### ISSUE THREAD

**Issue by flowip** [cocos2d/cocos2d-objc#699]
Emoji smiles are monochromatic in CCLabelTTF.
UILabel shows colorful smiles.

**Comment by slembcke** [comment]
Since most labels are really just alpha and then recolored using the GPU, Cocos2D is trying to be clever by saving memory and drawing the text as black and white.

Take a look at [CCLabelTTF updateTextureOld] for how it handles color vs. black and white. As a workaround in the current version, you can set the font color to something other than pure white to force it to use an RGBA texture instead.

The emoji use case is pretty small, but we might want to think about having an override?

**Comment by flowip** [comment]
Thank you. 
I changed color to RGB (254,254,254) and it works fine.
Other way is to change 'BOOL useFullColor = NO' in 'CCLabelTTF.m' to 'YES'. But i don't think it's good practice to change framework source code.

**Comment by slembcke** [comment]
This has been resolved in develop-v4 since we stopped supporting alpha only textures.
