### ISSUE TITLE
Cocos2D Installer 3.0.0.app on completion opens Safari always!

### ISSUE THREAD

**Issue by MKGitHub** [cocos2d/cocos2d-objc#716]
Cocos2D Installer 3.0.0.app on completion opens Safari always!
My default set browser is Chrome :-)

**Comment by ghost** [comment]
The issue is probably connected with install.sh script under ../installer/ directory.

``` sh
 35 # Landing Page, @todo Needs a nice welcome page
 36 open http://www.cocos2d-iphone.org/getting-started/
```

However according to the manual page it should be correct.
https://developer.apple.com/library/mac/documentation/Darwin/Reference/Manpages/man1/open.1.html

This command without any parameters should open URL in the default application for its type (as determined by LaunchServices).

There is even an example on the official man page - check below.

```
"open http://www.apple.com/" opens the URL in the default browser.
```

**Comment by cocojoe** [comment]
Nothing wrong with script, check your defaults.  Just tried opens in Chrome for me.

**Comment by MKGitHub** [comment]
Strange, on both my Macs Chrome is set as default but Safari opens.
