### ISSUE TITLE
Default blend mode incorrect for CCNodeColor

### ISSUE THREAD

**Issue by vlidholt** [cocos2d/cocos2d-objc#727]
CCNodeColor and CCDrawNode are not correctly displayed. Probable cause is an incorrect blend mode, they cannot use the same blend mode as sprites as they haven't got premultiplied alpha. Only affects transparent nodes.

At least this is my guess for what's incorrect.

**Comment by slembcke** [comment]
Hmm. Looks like the issue was just that I forgot to premultiply the vertex colors. There is still something not quite right about some gradients though:

The gradient in the middle should fade to grey. The method that calculates the gradient values is the same as 3.0 though. I'll port the test back to 3.0 tomorrow morning. Maybe it was broken then too?
![gradient issue](http://files.slembcke.net/upshot/upshot_ZKKUi43v.png)

**Comment by vlidholt** [comment]
It's quite possible the gradients have been broken since a long time ago.

**Comment by slembcke** [comment]
Did some more testing. There were two issues in 3.0. The vertex colors were not pre-multiplied before interpolation and the blending did not completely cover the rectangle. It looks like the issue has existed since the class was created.

Gradients from various colors to transparent white. Classic alpha interpolation issue. Since it's not visually obvious unless doing transparent white on black like this, I'm not very surprised that nobody noticed until now. The other issue is that the vertical gradient in the middle doesn't fade all the way out.
![3.0](http://files.slembcke.net/upshot/upshot_VZphzuET.png)

I fixed the interpolation by pre-multiplying the vertex colors in 3.1. Should I fix the vertical gradient issue too or leave it working like 3.0?
![3.1](http://files.slembcke.net/upshot/upshot_IKasat0C.png)

**Comment by slembcke** [comment]
Fixed the gradient issue on Friday. There was CCNodeGradient.compressedInterpolation that would change the gradient interpolation usually by a small and very poorly defined amount. Instead I made that property a no-op and made it always interpolate the entire color range across the rectangle.

**Comment by slembcke** [comment]
Sounds like there are still issues with CCDrawNode. I made tests... but I'll have to double check the tests.

**Comment by slembcke** [comment]
It was more vertex color premultiplication issues hidden by more inconclusive tests. Fixed now for sure.
