### ISSUE TITLE
Buttons in scrollview, can result in touches not working.

### ISSUE THREAD

**Issue by Birkemose** [cocos2d/cocos2d-objc#737]
If you scroll the scroll view, release your finger and while the scroll is still moving tap the button, then no more touches will work except for manoeuvring the scroll view.

**Comment by ghost** [comment]
Just encountered this bug now. I commented on another issue that was marked closed (seems this issue has come up multiple times). Figured I'd post on an issue that is still open.

Might be because CCScrollView is using a UIPanGestureRecognizer. Maybe the pan gesture is using a the same UITouch object that cocos2d is using and UIPanGestureRecognizer steals the touch? Just a guess. I didn't look too deeply into CCScrollView or how touch handling is being sorted before sent to nodes.

**Comment by slembcke** [comment]
This was fixed a few months ago.
