### ISSUE TITLE
CCFileUtils cleanup.

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#798]
CCFileUtils needs no introduction. It's grown into a mess that nobody wants to touch. It has _way_ too many configuration options and way too much undefined behavior. Ex: If you configure multiple devices to use the same suffix, which device's metadata (content scale, etc) should it consider the file to be associated with?

There was some discussion in the past about what we could do to clean it up, but the changes were always pretty significant. We can't do those now without breaking the API and making things even worse.

At this point, I think there are a few things we can improve. Ideally we can make it work well enough people rarely need to modify the defaults. Then in the future (4.0 or whenever) we can reduce the configuration complexity or remove much of it completely.
- **Enable both suffixes and directories by default:** Managing files in directories by hand is very tedious compared to suffixes, but SpriteBuilder uses directories. It would be nice if you could just mix and match and have the mode cause CCFileUtils to pick searching by directory or suffix first. Enabling both has pretty limited side effects if the existing mode variable is used as a priority.
- **Optionally treat spritesheets as directories:** SpriteBuilder does this with carefully crafted .plists, but this is quite difficult to do on one's own with existing tools. It's frustrating to deal with name collisions between sprite sheets, and it never occurred to me that there is a simple solution to this until @Birkemose brought it up. (You still have code for this Lars?)
- **`[CCSpriteFrameCache registerSpriteFramesFile:]`:** Related to the previous point, this method should not be required if using `spritesheet/frame.png` format. This is a direction we need to move in to fix memory issues with sprite frames. (Explicitly loaded sprite frames and thus their textures can never safely be uncached)

These changes all have very limited side effects yet remove the need for most of the CCFileUtils configuration that I've seen people attempt. They can all be implemented in a backwards compatible way.

References:
https://github.com/cocos2d/cocos2d-iphone/issues/474

**Comment by Birkemose** [comment]
The idea was not that complicated, but it worked surprisingly well, was very flexible, and made it easy to switch from folders during development, to sprite sheets for release.

When loading a file, the full path was taken, ex pathApplication/pathB/pathC/file.png.
The file loader then scanned backwards through the path components, until it found a match. For any folder path, it also tried if there was a matching sprite sheet.

Prior to this, a list of extensions had been set up. Let us assume that the file loader will first look for “-hd” and then for no e extension.
This would lead the file loader to look for the following files

pathApplication/pathB/pathC/file-hd.png
pathApplication/pathB/pathC/file.png
pathApplication/pathB/pathC-hd.plist
pathApplication/pathB/pathC.plist
pathApplication/pathB-hd.plist (the file would then have to be named pathC/file.png in the sprite sheet in order for it to load correctly)
pathApplication/pathB.plist

Any file entry was saved with both the plain name (file.png), the actual extension name (file-hd.png), and the path from application (pathB/pathC/file.png), so that any entry would work in loadWithImageNamed. The user would be free to have multiple identically filenames, in several folders, and easily access them. While it still would be possible not to, this would endorse programmers to use more path information when loading resources, which is impossible now, and weird if you ask me. If more files with the same name were added, file.png would be overwritten with a new entry, but this would not matter, as the user then could access the individual files through the full path. Maybe a warning should be issued.

Finally, as for the extension loading sequence, it was set according to device, with an according scale. Very very simple and flexible.

For an non-retina iPad, this could be
1) “-ipad” : scale = 1
2) “” : scale = 2
3) “-ipadhd”: scale = 0.5

During development, the user only has file.png, which will then be loaded and scaled \* 2. Later in development when he adds file-ipad.png, it will automatically be used, and scaled *1. This also means that it gets very very easy to create an application with only one set of assets. A feature that is sourly missed at the moment.

As I wrote some time back, one of my ideas was to make this a separate resource loader, to not break old functionality. Right now it would be possible to add a new resource loader to the -ext repo, and people could then make up their own mind on what they want to use.

/Birkemose

Den 29 May 2014 kl. 23:26 skrev Scott Lembcke notifications@github.com:
