### ISSUE TITLE
(v3.1) Spritesheets are loaded flipped on y axis, framecache coordinates are now wrong

### ISSUE THREAD

**Issue by chadwyk** [cocos2d/cocos2d-objc#808]
Spritesheets are being loaded flipped on y axis, but when you load a plist of coordinates it doesn't reflect changes to the y axis, so when you load a sprite from sharedSpriteFrameCache, the wrong section of the spritesheet is displayed.

More info here:
http://forum.cocos2d-iphone.org/t/3-1-rc1-spritesheet-coordinates-are-off/13735/2

**Comment by slembcke** [comment]
Already answered in the forum thread, but worth repeating here.

This is due to a fix for how Cocos2D handles OpenGL textures in 3.1. Cocos2D used to expect upside down PVR files in the past. Regular image formats such as PNG and JPEG are unaffected since they can easily be loaded in whatever orientation is required at loading time. PVR files are basically a block of memory that you pass directly to OpenGL and cannot be fixed at runtime.

Most tools for working with PVR files such as PVRTexTool or Texture Packer include an option to flip the output texture.
