### ISSUE TITLE
TTF Label issues in iOS 8

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#809]
http://forum.cocos2d-iphone.org/t/problem-with-ios8-and-cclabelttf/13744

Summary:
Some (or all?) TTF labels don't show up on iOS 8.

**Comment by jonnyijapan** [comment]
I can confirm the problem. I am using a custom font. Works well on all other setups, but with iOS 8 beta 2 (iPhone 5s) the labels don't show up. I haven't looked into the issue more than that. Maybe the custom font is the culprit, maybe not.

Update: It seems to be related to custom fonts. Compiling with Xcode 6 and the new iOS SDK and "Helvetica" as font, the labels show up. If I use my custom font they do not. Maybe something with fonts in iOS 8 changed... maybe it's a bug in iOS 8 - in which case someone should report that to Apple :-)

**Comment by jonnyijapan** [comment]
This problem also appears on the old Cocos2d-iphone v2.x engine. CCLabelTTF with custom fonts don't show up. I will really have to deal with this problem for a couple of published games soon, unless Apple fixes/changes iOS8 to make it work.

**Comment by jonnyijapan** [comment]
This seems to be related: https://github.com/cocos2d/cocos2d-iphone/issues/645

**Comment by ccwasden** [comment]
The issue still exists in beta 3.. it's making me a little nervous for my published apps as well. Devs outside of cocos2d seem to be having the same problem, evidenced by this ios8 forum post https://devforums.apple.com/message/995882#995882

**Comment by jonnyijapan** [comment]
It's not limited to 64 bit. I just tried it on a 32bit iPad mini. No custom labels show up.
These are the devices I have tested so far with iOS 8 (beta 3):
iPhone 5s (space grey ;-) )
iPad mini (first generation, no retina, 32 bit)

And, it appears in both Cocos2d-iphone v3.x as well as Cocos2d-iPhone v2.x.

**Comment by jonnyijapan** [comment]
I just wrote a sample app only using UIKit and indeed custom fonts don't work. This looks very much like it's not a problem with Cocos2d! I have reported this bug to apple including the sample app. I suggest you all do too... there are probably quite a few live apps that will be affected by this if Apple does not fix iOS 8. Who knows however if they will fix it or not - worst case scenario I guess we will just have to ignore custom fonts for a while in our apps.

**Comment by ccwasden** [comment]
Looks like this is fixed in beta 4!

**Comment by jonnyijapan** [comment]
Yes fixed. This can be closed.

**Comment by ghost** [comment]
One of my TTF fonts isn't displaying on iOS 8. When I run it on iOS 7 it works still. I'm running Xcode 6 GM.

I have 3 custom TTF fonts showing in the same scene. Two out of the three work on iOS 8, which is kind of unfortunate since that makes it harder to reproduce the issue.

Looks like Apple changes the way iOS identifies certain kind of fonts. I have a custom font named something like:

"MyFontFamily- FontName.ttf".

On iOS 7 that works. On iOS 8 if I change the filename to:

"MyFontFamily--FontName.ttf" that works.

Sadly, fixing the font for iOS 8 causes it to not work on iOS 7. Guess I have to put in some ugly workaround code.

**Comment by slembcke** [comment]
This was fixed in 3.3.

**Comment by jonnyijapan** [comment]
I have seen a similar problem again since yesterday. One of our apps went live on the app store yesterday, and someone tweeted a screenshot where labels are missing/invisible, just like they were when the above issue was happening back on iOS 8 beta versions up till 3. The missing labels use a custom font. The app in question supports iOS 7.1 and above. I can't confirm anything since I haven't been able to reproduce the issue but the only thing I can think of is this problem. Now if someone uses iOS 8.0 beta 3 and below that might happen... but the likeliness is pretty low of that anyway, and anyway if someone uses iOS 8.0 beta that's his/her fault too :-P

Still 1, the error might be somewhere else completely...

Still 2, if the problem is the same as this issue, it might mean it's STILL not a problem with Cocos2D per se, AND, iOS 8 STILL don't play nice with custom fonts... under some unknown circumstances. Anyway, I think the problem caused yesterday does not happen very often.
