### ISSUE TITLE
CCLabelTTF property outlineColor doesn't work

### ISSUE THREAD

**Issue by agro1986** [cocos2d/cocos2d-objc#811]
Create a red CCLabelTTF, then set its outline color:

label.color = [CCColor redColor];
label.outlineColor = [CCColor whiteColor];
label.outlineWidth = 2.0f;

Outline color will be drawn but the color will be red, not white.

OS X 10.9.3
XCode 5.1.1
iOS 7
Cocos2D 3.1 RC

**Comment by slembcke** [comment]
It's a little confusing since there are a lot of colors involved, but that is the intended behavior.

The CCNode.color property is a tint color that nodes should apply when they render themselves. It tints both the outline and fill color for CCLabelTTFs. If you want to change the text fill color, you need to use CCLabelTTF.fontColor. You can set that without affecting the CCLabelTTF.outlineColor property.

**Comment by lsmpascal** [comment]
Hi.
I've got an issue on this : the CCLabelTTF outlineColor appears always black whatever the color I put, even if I use fontColor (and not "color"). If I get rid of the fontColor, the outline stay black.

```
CCLabelTTF  * label = [CCLabelTTF labelWithString:@"a text" fontName:@"JetSet-Italic.ttf" fontSize:15];
label.anchorPoint = ccp(0.5, 1);
label.positionType = CCPositionTypeNormalized;
label.position = ccp(0.5, -2);
label.fontColor = [CCColor redColor];
label.outlineWidth = 1;
label.outlineColor = [CCColor whiteColor];
[self addChild:label];
```

Any idear ?
Note : I'm using cocos2d-iphone version 3.0.alpha.
