### ISSUE TITLE
Apply tint color to CCDrawNode

### ISSUE THREAD

**Issue by slembcke** [cocos2d/cocos2d-objc#821]
http://forum.cocos2d-iphone.org/t/ccdrawnode-changing-alpha-or-opacity/13469

This would be pretty easy to do with a custom vertex shader for draw nodes. I've been considering doing it anyway to avoid the CPU based vertex transform.

**Comment by slembcke** [comment]
I implemented this here, though it hasn't been tested heavily yet:
https://github.com/slembcke/cocos2d-iphone/commit/3c12583b2a01b71d680154ed9ab0a7b29286b861

**Comment by narbodon** [comment]
I found that by using the CCDrawNode's _color property, the tint wouldn't be applied in situations where the draw node was a child of another node, whose opacity was being cascaded to the child draw node. Using the _displayedColor property fixes that, however. (This is because in CCNode's updateDisplayedOpacity: and updateDisplayedColor: methods, which are used for cascading, only the displayedColor property is modified, not the color property, of course.)

I've also noticed a massive increase in CPU time needed to render large sets of CCDrawNodes now, using this updated draw method and vertex shader.

**Comment by slembcke** [comment]
Ugh. Color cascading, of course. One of my least favorite features. -_-

"to render large sets of CCDrawNodes" Do you mean rendering a CCDrawNode with many primitives in it or many CCDrawNodes? Unfortunately that's the tradeoff. To batch them the vertexes have to be processed on the CPU. To get better vertex throughput, you need to process them in the vertex shader. I suppose it wouldn't be hard to support both modes, but I'm not really excited about making the public interface more complicated than it needs to be.

**Comment by slembcke** [comment]
Hmm. Thinking about it some more, I'll add a boolean property to the private API. It's only a couple extra lines of code now, but I'm going to hold off moving it to the public API for now.

**Comment by narbodon** [comment]
I mean the latter, rendering many CCDrawNodes.

**Comment by slembcke** [comment]
This was merged into the develop branch a couple weeks ago.
