### ISSUE TITLE
Clipping node has incorrect default alpha threshold

### ISSUE THREAD

**Issue by vlidholt** [cocos2d/cocos2d-objc#846]
See: http://forum.spritebuilder.com/t/cocos2d-v3-1-ccclipnode-not-working/1299

**Comment by slembcke** [comment]
Ugh. So it turns out the 3.1 behavior is actually "correct" for what it's worth.

If they were allowed, a negative threshold would draw everything. A threshold of 0.0 would mask "fat" versions of the sprites, 0.999 would draw very thin sprites, and a threshold of 1.0 should draw nothing at all.

Both versions use a default alpha threshold of 1.0 which should mean that the mask should always be empty. This works correctly in 3.1 (though there is some gross flickering due to pixel shader precision). In 3.0 and earlier it disables the alpha test and masks all your sprites as if they had no alpha channels. Neither useful nor well defined. That broken, poorly defined behavior is what happens when you use the default threshold.

0.5 is a much more sensible default threshold, but I didn't want to change it. I didn't realize that I'd accidentally fixed a bug that affected the default behavior however. :-\ Any thoughts on what to do? Emulate the old, buggy, default behavior or fix it?
