### ISSUE TITLE
CCLabelTTF outlinecolor doesn't work well

### ISSUE THREAD

**Issue by huabin** [cocos2d/cocos2d-objc#858]
if i use like this

``` objc
cclabelttf.outlineColor = [CCColor colorWithCcColor3b:ccWHITE]; 
```

it works well, but i use like this

``` objc
cclabelttf.outlineColor = [CCColor colorWithUIColor:[UIColor colorWithRed:120/255 green:120/255 blue:250/255 alpha:1.0f]];
```

and other ways, it doen't work, always show black color.

**Comment by huabin** [comment]
just use

``` objc
cclabelttf.outlineColor = [CCColor colorWithRed:120/255 green:120/255 blue:250/255 alpha:1.0f];
```

also has this bug.

**Comment by richardgroves** [comment]
Isn't that because 120/255 (for example) will be performed in integer
arithmetic and therefore give 0 as the answer? [The calculation is
performed in the simplest type that matches both arguments: in this case
'int', and then the result of that is converted to float when passed as an
argument]

Do it as 120.0f/255.0f and I suspect it will work fine.

On Sun, Jun 29, 2014 at 1:22 PM, bingeh notifications@github.com wrote:

> just use
> 
> cclabelttf.outlineColor = [CCColor colorWithRed:120/255 green:120/255 blue:250/255 alpha:1.0f];
> 
> also has this bug.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cocos2d/cocos2d-iphone/issues/858#issuecomment-47453018
> .

## 

Richard Groves
Technical Director | NoodlFroot

M: +44 (0)7962 054 163

www.noodlfroot.com

NoodlFroot Limited is a company registered in England and Wales with
registration number 07245048.
Registered office: 145-157 St John Street, London, EC1V 4PY.

**Comment by huabin** [comment]
@richardgroves I just found that mistake of mine, but thanks all the same.
