### ISSUE TITLE
Issue with CCRenderStateCache + CCLabelTTF

### ISSUE THREAD

**Issue by Ben-G** [cocos2d/cocos2d-objc#890]
In Cocos2D 3.1 a problem with the CCRenderStateCache in combination with CCLabelTTF occurs. When CCLabelTTF is updated frequently every generated texture results in a new cached render state (I'm aware that CCLabelTTF's should not be used for frequently updating test, however this is a more general issue with the way the cache is set up). In a test case where a CCLabelTTF gets updated every single frame, the memory usage of the app sums up to a couple hundred megabyte after a few minutes. Mainly because each cached CCRenderState keeps a reference to a generated OpenGL texture.

When a memory warning occurs the cache is purged correctly but caching all the render states creates a fairly big performance drain before the memory warnings occurs (I need to test the performance drain on an actual device).

I'm not very familiar with the new rendering engine yet, but based on what I have seen so far I have two suggestions that I think would be an improvement to the render state caching.
## Use NSCache within CCCache instead of NSMutableDictionary

Currently `CCCache` uses an `NSMutableArray` to store the cache content:

```
     NSMutableDictionary *_cacheList;
```

I think it would be better to use a `NSCache` and let each `CCCache` subclass configure that `NSCache`. That would allow the `CCRenderStateCache` to set a reasonable limit of cached states and caching more render states would cause old/unused ones to be purged, before a memory warning is provoked.
## Allow CCNode subclasses to decide to create uncached render states?

Specific CCNode subclasses probably know that they update their texture very frequently and should maybe be able to exclude themselves from render state caching? 

Maybe someone else has better suggestions?

**Comment by Birkemose** [comment]
I guess the behaviour is correct (the cache growing when adding a new texture), unless the cache is purged. So I guess the fix is merely a matter of checking the cache for unused objects on each loop. Scott would be the authority on that.

As for NSCache, it can not be used for freely purgeable functionality, unless you use the NSDiscardableContent protocol on all cacheable objects, which I do not think is a good idea. The NSPurgeableData basically exposes this kind of functionality, but as ARC guarantees that unused objects are set to nil, using NSMutableDictionary works exactly like NSPurgeableData would, without us having to be forced to use a specific protocol. 

I agree that special nodes should be able to exclude themselves from being processed by the render engine, if they don’t already. I haven’t checked.

**Comment by slembcke** [comment]
This is fixed in the develop branch, but not in a release yet. The inherited behavior for nodes is to assume that they want to create cached (shared) renderstates. The fix was a pretty straightforward override of the renderstate method:

https://github.com/cocos2d/cocos2d-iphone/blob/develop/cocos2d/CCLabelTTF.m#L332

Uff. Need to get that out in a release...

"matter of checking for unused objects on each loop" I tried it and the performance was surprisingly bad. O_o That's part of the reason it's as greedy as it is. I'm not specifically opposed to NSCache, but I don't see how it can be made to work like CCCache does where it doesn't remove live objects from the cache. NSDiscardableContent requires adding an extra level of retain counting that I'm not convinced is helpful either. I'd love to be proved wrong if it means improving the cache without reinventing the wheel ourselves.

**Comment by Ben-G** [comment]
Yep, it would be great if NSCache would have simple way to stop objects from eviction. Seems like an oversight. The CCLabelTTF fix is most important for know. Thx @slembcke 
Can you close when the fix is merged?

**Comment by slembcke** [comment]
Merged or released? It's in the 3.1 branch now.

**Comment by Ben-G** [comment]
That's fine. Thx!
