### ISSUE TITLE
Can't use alpha into setBackgroundColor of CCButton

### ISSUE THREAD

**Issue by ckjbeos** [cocos2d/cocos2d-objc#894]
According to birkemose
( http://forum.cocos2d-swift.org/t/bug-v3-1-ccbutton-and-alpha-color/14421 )

Setting opacity into setBackgroundColor with alpha channel has no effect, and that setBackgroundOpacity should be used instead.

code :
CCButton *speedModedButton = [CCButton buttonWithTitle:NSLocalizedString(@"speed", nil) spriteFrame:initialSpriteFrame highlightedSpriteFrame:initialSpriteFrame disabledSpriteFrame:initialSpriteFrame];[speedModedButton setBackgroundColor:[[_appDelegeate getColorArrayForTheme:_colorTheme] objectAtIndex:C_0101100_COLOR_BUTTON] forState:CCControlStateNormal];

in the code, [[_appDelegeate getColorArrayForTheme:_colorTheme] objectAtIndex:C_0101100_COLOR_BUTTON] is a CCColor object containing an alpha value set to 0.25f but no effect.

Regards.
Cedric - Pixs'n Bits

**Comment by slembcke** [comment]
Ah, this issue. The short version is that .color is "working as intended", and that you want .colorRGBA instead.

So Cocos 1.x and 2.x had separate .color (RGB8) and .opacity properties. In Cocos 3.x we made a universal floating point RGBA color type to try and remove some of the inconsistencies where nearly every class used a different color type. (RGB, RGBA, float, unsigned byte, etc)

Since the new CCColor type was going to have alpha, it seemed to make sense that setting the color would set the alpha too. After a lot of discussion (it's on GitHub... somewhere...) it was decided that the color property shouldn't set the alpha. An example problem was that the tint action would no longer be able to change the tint of a color without affecting the opacity.

I personally think of color as including the alpha, so I was on the ".color should set the alpha" side of the fence. The compromise that made everybody happy was to add a .colorRGBA property that sets both.
