### ISSUE TITLE
Periodic crash on scene switch CCNode enumerating children array while mutated.

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-objc#937]
I'm upgrading a project to 3.1. I keep running into this issue periodically on  a scene that has a lot of children.

When switching out of the scene, I get a crash due to enumerating the children's array while mutating it. In CCNode's dealloc method I see:

 for (CCNode\* child in _children)
        child.parent = nil;

If I comment that out, I do not get a crash. The parent property is weak, there should be no reason to explicitly set a node's parent to nil in dealloc. ARC should take care of it. 
If I comment that enumeration out of the dealloc method I do not hit the crash.

I also noticed that the parent property is actually declared unsafe_unretained? Usually it is better to use weak.

**Comment by Birkemose** [comment]
You are correct, ARC will handle this. Just comment out the code. This looks like some abandoned debug code or something.

**Comment by Panajev** [comment]
> > If I comment that out, I do not get a crash. The parent property is weak, there should be no reason to explicitly
> > 
> > I also noticed that the parent property is actually declared unsafe_unretained?

Is the patent property weak or unsafe_unretained? 

[web [iPhone msg]]

**Comment by ghost** [comment]
parent property is declared unsafe_unretained by default for the 'weak reference'. In my project I changed it to __weak on the ivar (and weak for the corresponding property declaration). Usually it is better to declare a weak reference using the __weak keyword under ARC, as the compiler will set your weak pointer to nil for you instead of leaving it dangling.

**Comment by slembcke** [comment]
@Birkemose and I talked about this on Friday a little. It's definitely not correct. Looking back in the history a couple years, I think it may have been a bug in 2.x as well, though it was using CCArray instead of NSArray so it might have simply been undetected.

I agree that the parent property should just become weak instead. There is a small overhead for dealing with weak references, though I'd be surprised if it is much worse than iterating the array of children in the dealloc method.

**Comment by iMobCoding** [comment]
You should merge that into the v3.2 branch. Right now, only develop, v3.0 & v3.1 branches have weak parent and removed those lines above
