### ISSUE TITLE
CCTextureCache : removeTextureForKey  abandons memory

### ISSUE THREAD

**Issue by YvesLeBorg** [cocos2d/cocos2d-objc#956]
context : porting a coco2d 2.1 project to 3.2rc , app designed with 'just in time' texture loading, unload as fast as possible, to keep memory footprint under iOS memory pressure radar.

code snippet : from a tooltip popup node, pops upon a long touch on just about anything that has a toolTip property.

problem : when i use removeTextureForKey, the process size grows 800k every time, but the texture is vanished from the cache. 

snippet:

```
if (_backgroundImageName) {

    // this is safe, removeTextureForKey fails silently

    [[CCTextureCache sharedTextureCache] removeTextureForKey:_backgroundImageName];
    TRACE(@"Remove texture  for key [%@]", _backgroundImageName);   // <-- causes allocation increase
                                                                    //     but texture vanished from cache
//    [[CCTextureCache sharedTextureCache] removeUnusedTextures];   // <-- no memory increase but texture
                                                                    //     stays in cache

}
```

log: (with removeTextureForKey) and process size increase

-[GEToolTipProviderImpl displayToolTip:withFont:fontSize:avoidingLocation:] : Selecting med. image [menu_map_tooltip.png]
-[GEToolTipProviderImpl displayToolTipWithNode:avoidingLocation:] : Texture cache after tooltip popup   : 
-[CCTextureCache cachedTextureInfo] : "menu_map_tooltip.png"    id=4    560 x 176   @ 32 bpp => 385 KB
-[CCTextureCache cachedTextureInfo] : "menu_unitBackground.png" id=7    184 x 264   @ 32 bpp => 189 KB
-[CCTextureCache cachedTextureInfo] : "titleScreen.png" id=6    1136 x 768  @ 32 bpp => 3408 KB
-[CCTextureCache cachedTextureInfo]: total  3 textures, for 3982 KB (3.89 MB)
-[GENodeLayoutHelper dealloc] : dealloc [1]/[0BE531D0], [0] left.
-[GEToolTipProviderImpl nukeToolTipNode] : removing  toolTipNode
-[GEToolTipProviderImpl nukeToolTip] : Remove texture  for key [menu_map_tooltip.png]
-[GEToolTipProviderImpl nukeToolTip] : Texture cache after tooltip removal : 
-[CCTextureCache cachedTextureInfo] : "menu_unitBackground.png" id=7    184 x 264   @ 32 bpp => 189 KB
-[CCTextureCache cachedTextureInfo] : "titleScreen.png" id=6    1136 x 768  @ 32 bpp => 3408 KB
-[CCTextureCache cachedTextureInfo]: total  2 textures, for 3597 KB (3.51 MB)

log: (with removeUnusedTexture)

-[GEToolTipProviderImpl displayToolTip:withFont:fontSize:avoidingLocation:] : Selecting med. image [menu_map_tooltip.png]
-[GEToolTipProviderImpl displayToolTipWithNode:avoidingLocation:] : Texture cache after tooltip popup   : 
-[CCTextureCache cachedTextureInfo] : "menu_map_tooltip.png"    id=4    560 x 176   @ 32 bpp => 385 KB
-[CCTextureCache cachedTextureInfo] : "menu_unitBackground.png" id=7    184 x 264   @ 32 bpp => 189 KB
-[CCTextureCache cachedTextureInfo] : "titleScreen.png" id=6    1136 x 768  @ 32 bpp => 3408 KB
-[CCTextureCache cachedTextureInfo]: total  3 textures, for 3982 KB (3.89 MB)
-[GENodeLayoutHelper dealloc] : dealloc [1]/[0BF58090], [0] left.
-[GEToolTipProviderImpl nukeToolTipNode] : removing  toolTipNode
-[GEToolTipProviderImpl nukeToolTip] : Texture cache after tooltip removal : 
-[CCTextureCache cachedTextureInfo] : "menu_map_tooltip.png"    id=4    560 x 176   @ 32 bpp => 385 KB
-[CCTextureCache cachedTextureInfo] : "menu_unitBackground.png" id=7    184 x 264   @ 32 bpp => 189 KB
-[CCTextureCache cachedTextureInfo] : "titleScreen.png" id=6    1136 x 768  @ 32 bpp => 3408 KB
-[CCTextureCache cachedTextureInfo]: total  3 textures, for 3982 KB (3.89 MB)

notes:
- 800K is twice the size of the texture
- when using removeUnusedTextures, there is nothing left in my code that refers to the texture, somehow it must be CCTextureCache itself or yet another cache cache that clings on.
- memory footprint measured with instruments (allocations), instruments(Monitor), and my own footprint measurement (permanently displayed during debug, a doctored CCDirector ). All three are in violent agreement.
- Instruments(Leaks) , for what its worth, shows no leaks.

**Comment by Birkemose** [comment]
I just checked this, and as far as I can tell, the texture cache is working as expected.  
If you remove the texture from the cache, but accidentally retains it elsewhere, you will experience the behaviour you describe, so my guess would be, that that is you problem.

**Comment by YvesLeBorg** [comment]
@Birkemose nope, just did a very localized test, this repeats. I applied a patch (re cclabelttf, maybe i did this mid-flight and that caused the issue with my configuration).  I'll harness my project with the current dev branch, see what gives. Also, how could my retaining accidentally cause 2x texture size to be alloc'ed and abandoned?

**Comment by slembcke** [comment]
Uh oh. :-\ I think I know what is going on here. Looking into this right now.

**Comment by YvesLeBorg** [comment]
@slembcke thanks ... this is way above my pay scale :) i got some nasty zombies in CCRenderer when running with this morning's dev branch.

**Comment by slembcke** [comment]
I caused a bug in the render state cache since the last 3.1 release. The cache was never releasing its states, and that was causing the textures to be leaked. The texture cache and it's tests were working as expected, so it got missed.

Fixed + more automated unit tests here: 8f4d8c196b2d46d5c8899673e0260dbfb63c68a6

_BUT_

Some things to keep in mind:
- Direct access to the texture cache was deprecated in 3.0. I would strongly recommend managing temporary textures outside of the cache for future code.
- If you want to remove textures at will, you'll also need to flush the render state cache which is also private. (Not making it difficult to do this on purpose, but the cache is meant to be greedy until iOS sends a memory warning)

@YvesLeBorg When you say "zombies" what do you mean exactly? Leaked memory? Dangling pointers?

**Comment by YvesLeBorg** [comment]
@slembcke Dangling i think, was running without zombies, just got hard crash in draw. 

here is a ss, 
![screen shot 2014-09-02 at 5 01 37 pm](https://cloud.githubusercontent.com/assets/8483908/4125728/86553c0e-32e4-11e4-8a42-a6e6ac5ac8b6.png)

some points:
- i chose carefully when adopting cocos2d some time ago (version 0.9.x). Being able to cache some and not cache some others was key to my decision. My apps (very 'non casual' RPG games) are memory hungry. I traded off time vs space, chosing to load just-in-time so that the bulk of memory be available for my object space, AI, etc ... Everything is clocked at 30FPS, buying me time to load carefully. Textures are .pvr.gz (3600 sprite sheets). pvr for load speed, frames are optimized for 30fps game sequencing.
- there are many many slocs dedicated to flushing textures from cache (simply because they were always cached in the past). I know i cant afford caching for the combat scenes and map scenes with soldiers fighting/walking/idling there. Way too many pixels if i cache the skills, walk, and idle stance textures, the app gets nuked by iOS.
- Of course, it is your call on the caching policy. I just dont know what you mean by 'managing temporary textures' outside the cache. How would i do that ? I need the cache and draw call batching for some stuff, so your current caching policy works for me. However, for other stuff, i must manage caching myself.

**Comment by slembcke** [comment]
@YvesLeBorg I looked into this a bit more last night and thought about it more.

I had forgotten how inadequate the public API is for managing textures without the cache. With the exception of PVR textures, you cannot load textures from files without using the cache. I recently was working on changes to improve texture loading, but ended up dumping the branch because it required changing the public API somewhat and required a lot of private API changes. I was about to suggest using one of the methods from that branch until I realized that it doesn't exist in the main branch. :-\ So you are right. You don't really have a choice but to do what you are doing. :(

Because of how the texture cache interacts with the sprite frame cache and some of the other APIs, it's _really_ hard to change or improve it. There are even a few bugs that there isn't a good solution to without changing the public API. There are a lot of fixes and improvements that have been talked about that are probably going to have to wait until v4 when we can fix the API.

So...

After thinking about it a little more, I think the next best thing I can do is make the render state cache not retain the textures at all. Then the textures can simply be managed like before. This morning I rewrote the cache to use a separate key class, and it seems to be working.

As for the `nil` vertex buffer. Do you have any more information on that? Now that Cocos can render on GL or Metal, it detects which set of graphics classes to use at startup time. My best guess is that the graphics buffer class was `nil`. It's supposed to happen before the view is set up, so I'm not sure what exactly would cause it to happen.

**Comment by YvesLeBorg** [comment]
@slembcke hmmm, i may have caused that by removing from the build some classes that were not compiling ... t'is always a pain to 'cut and paste' a new codebase into my project space because of the disincarnate nature of the .xcodeproject files. Have to track new classes, those that were removed, which have compiler options, etc etc etc . I'll try to create a minimal project that can be uploaded privately for you to examine ... either i broke the build, or there is something broken in it. Might as well chase it now.  Will be awhile, that port to 3.2 is turning into a major pass-time for me :)
